// web/src/pages/Admin.vue
<!--
  用户管理页 Admin.vue（仅 admin 可见）
  Admin page Admin.vue (admin only)
  账号开通、角色/权限配置、改密、启禁用、以及为他人账号代配战法参数。
  Create accounts, set role/perms, reset passwords, enable/disable,
  and configure per-account strategy params on behalf of users.
-->
<template>
  <div class="admin-page">
    <h2>用户管理</h2>

    <!-- 开户表单 -->
    <div class="card">
      <div class="card-header">开通新账号</div>
      <div class="form-grid">
        <div class="form-row">
          <label>用户名</label>
          <input v-model="newUser.username" placeholder="登录名" />
        </div>
        <div class="form-row">
          <label>初始密码</label>
          <input v-model="newUser.password" placeholder="首次登录用" type="password" />
        </div>
        <div class="form-row">
          <label>角色</label>
          <select v-model="newUser.role">
            <option value="user">普通用户</option>
            <option value="admin">管理员</option>
          </select>
        </div>
        <div class="form-row">
          <label>权限</label>
          <div class="perm-checks">
            <label v-for="p in allPerms" :key="p" class="perm-check">
              <input type="checkbox" :value="p" v-model="newUser.perms" />
              {{ permLabel(p) }}
            </label>
          </div>
        </div>
        <div class="form-row">
          <label>有效期</label>
          <div class="expiry-row">
            <input v-model.number="newUser.expiresDays" type="number" min="0" placeholder="天数" :disabled="newUser.permanent" />
            <label class="perm-check">
              <input type="checkbox" v-model="newUser.permanent" /> 永久
            </label>
          </div>
          <span class="field-hint">填天数表示到期后自动失效；勾选"永久"则不过期</span>
        </div>
      </div>
      <button class="btn-primary" @click="createUser" :disabled="creating">
        {{ creating ? '创建中...' : '创建账号' }}
      </button>
      <span v-if="createMsg" :class="['feedback', createMsgType]">{{ createMsg }}</span>
    </div>

    <!-- 用户列表 -->
    <div class="card" v-if="users.length">
      <div class="card-header">账号列表</div>
      <div class="user-table">
        <div class="user-row" v-for="u in users" :key="u.id">
          <div class="user-main">
            <div class="user-name">
              {{ u.username }}
              <span :class="['role-tag', u.role === 'admin' ? 'role-admin' : 'role-user']">
                {{ u.role === 'admin' ? '管理员' : '用户' }}
              </span>
              <span v-if="!u.enabled" class="role-tag role-disabled">已禁用</span>
            </div>
            <div class="user-meta">ID: {{ u.id }} · 创建于 {{ fmtTime(u.created_at) }} · {{ expiryText(u) }}</div>
            <div class="perm-checks">
              <label v-for="p in allPerms" :key="p" class="perm-check">
                <input type="checkbox"
                       :checked="uPerms(u).includes(p)"
                       :disabled="u.role === 'admin'"
                       @change="togglePerm(u, p, $event)" />
                {{ permLabel(p) }}
              </label>
            </div>
          </div>
          <div class="user-actions">
            <button class="btn-mini" @click="toggleRole(u)">
              {{ u.role === 'admin' ? '降为普通用户' : '设为管理员' }}
            </button>
            <button class="btn-mini" @click="askResetPassword(u)">重置密码</button>
            <button class="btn-mini" :disabled="u.role === 'admin'" @click="toggleEnabled(u)">
              {{ u.enabled ? '禁用' : '启用' }}
            </button>
            <button class="btn-mini" :disabled="u.role === 'admin'" @click="askSetExpiry(u)">设置有效期</button>
            <button class="btn-mini" @click="openStrategy(u)">配战法参数</button>
            <button class="btn-mini btn-danger" :disabled="u.role === 'admin'" @click="askDeleteUser(u)">删除</button>
          </div>
        </div>
      </div>
    </div>

    <!-- 代配战法参数弹层 -->
    <div v-if="activeUser" class="modal-mask" @click.self="closeStrategy">
      <div class="modal">
        <div class="modal-header">
          <span>为 {{ activeUser.username }} 配置战法参数</span>
          <button class="btn-close" @click="closeStrategy">✕</button>
        </div>
        <div class="strategy-groups">
          <div v-for="group in strategyGroups" :key="group.key" class="card group-card">
            <div class="card-header">{{ group.title }}</div>
            <div class="form-row" v-for="f in group.fields" :key="f.k">
              <label :title="f.hint || ''">{{ f.label }}</label>
              <label v-if="f.type === 'switch'" class="switch">
                <input type="checkbox" v-model="activeStrategy[group.key][f.k]" />
                <span class="slider"></span>
              </label>
              <input v-else
                     v-model.number="activeStrategy[group.key][f.k]"
                     :type="f.type || 'number'"
                     :step="f.type === 'number' ? (f.step || 'any') : undefined"
                     placeholder="0" />
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn-primary" @click="saveStrategy" :disabled="strategySaving">
            {{ strategySaving ? '保存中...' : '保存该账号战法参数' }}
          </button>
          <span v-if="strategyMsg" :class="['feedback', strategyMsgType]">{{ strategyMsg }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import * as api from '../api/index.js'

// ── 状态 ──
const users = ref([])
const allPerms = ref([])
const creating = ref(false)
const createMsg = ref('')
const createMsgType = ref('ok')
const newUser = ref({ username: '', password: '', role: 'user', perms: [], expiresDays: 0, permanent: true })

const activeUser = ref(null)
const activeStrategy = ref({})
const strategySaving = ref(false)
const strategyMsg = ref('')
const strategyMsgType = ref('ok')

// 战法参数分组定义（与 Settings.vue 一致）
const strategyGroups = [
  {
    key: 'dragon', title: '龙头战法（权重合计≤1）',
    fields: [
      { k: 'f1_seal_weight', label: 'F1 首封权重', step: 0.05 },
      { k: 'f2_resonance_weight', label: 'F2 共振权重', step: 0.05 },
      { k: 'f3_premium_weight', label: 'F3 溢价权重', step: 0.05 },
      { k: 'f4_rs_weight', label: 'F4 强度权重', step: 0.05 },
      { k: 'pullback_max_pct', label: '最大回撤%', step: 0.01 },
      { k: 'breaker_sell_half_pct', label: '炸板减半%', step: 0.01 },
      { k: 'breaker_sell_all_pct', label: '炸板清仓%', step: 0.01 },
      { k: 'buy_pullback_sell_half_pct', label: '买入回撤减半%', step: 0.01 },
      { k: 'buy_pullback_sell_all_pct', label: '买入回撤清仓%', step: 0.01 },
      { k: 'buy_day_close_below', label: '买入日收盘低于%', step: 0.01 },
      { k: 'next_open_if_below', label: '次日开盘低于%', step: 0.01 },
      { k: 'take_profit_pct', label: '止盈%', step: 1 },
    ],
  },
  {
    key: 'double_bump', title: '双响炮战法',
    fields: [
      { k: 'first_break_volume_multiple', label: '一突量比', step: 0.1 },
      { k: 'second_break_volume_multiple', label: '二突量比', step: 0.1 },
      { k: 'adjust_vol_ratio_max', label: '调整量比上限', step: 0.5 },
      { k: 'position_weight', label: '调整深度权重', step: 0.05 },
      { k: 'ma_weight', label: '均线权重', step: 0.05 },
      { k: 'volume_weight', label: '量能权重', step: 0.05 },
      { k: 'double_bump_take_profit_pct', label: '止盈%', step: 0.01 },
    ],
  },
  {
    key: 'n_shape', title: 'N 形战法',
    fields: [
      { k: 'n_pattern_score_threshold', label: 'N 形态分阈值', step: 1 },
      { k: 'hard_stop_loss', label: '硬止损%', step: 0.01 },
    ],
  },
  {
    key: 'dragon_return', title: '龙回头战法',
    fields: [
      { k: 'stop_loss_pct', label: '止损%', step: 0.01 },
      { k: 'take_profit_pct', label: '止盈%', step: 0.01 },
      { k: 'max_hold_days', label: '最长持仓天数', step: 1 },
      { k: 'target1_multiplier', label: '目标1倍数', step: 0.05 },
      { k: 'target2_multiplier', label: '目标2倍数', step: 0.05 },
      { k: 'trailing_drawback', label: '移动止损回撤%', step: 0.01 },
    ],
  },
  {
    key: 'momentum', title: '动量分权重（合计建议=100）',
    fields: [
      { k: 'volume_price_weight', label: '量价权重', step: 5 },
      { k: 'macd_weight', label: 'MACD权重', step: 5 },
      { k: 'trend_weight', label: '走势权重', step: 5 },
      { k: 'momentum_gate_enabled', label: '动量提升才提醒', type: 'switch', hint: '开启后仅当动量分提升(或回落≤容忍差)才放行 双响炮/龙头/龙回头 战法信号；N形不受影响' },
      { k: 'momentum_delta_tol', label: '回落容忍差(分)', step: 1, hint: '动量分相对上一轮回落 ≤ 该值仍视为提升；设为0表示需严格不回落' },
    ],
  },
]

/** 权限位显示名 */
function permLabel(p) {
  const m = { research_approve: '研究审批' }
  return m[p] || p
}

/** 时间戳格式化 */
function fmtTime(ts) {
  if (!ts) return '-'
  const d = new Date(ts * 1000)
  return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0')
}

/** 有效期展示文本：永久 / 到期日(+剩余天数) / 已到期 */
function expiryText(u) {
  if (!u.expires_at) return '有效期：永久'
  const now = Date.now()
  const exp = u.expires_at * 1000
  if (exp < now) return '有效期：已到期'
  const days = Math.ceil((exp - now) / 86400000)
  return '有效期：' + fmtTime(u.expires_at) + '（剩 ' + days + ' 天）'
}

/** 设置有效期：prompt 输入天数，0=永久 */
function askSetExpiry(u) {
  const cur = u.expires_at ? Math.ceil((u.expires_at * 1000 - Date.now()) / 86400000) : 0
  const input = prompt(
    '为 ' + u.username + ' 设置有效期天数（输入 0 表示永久；当前' + (u.expires_at ? '剩余约 ' + (cur > 0 ? cur : '已到期') + ' 天' : '永久') + '）：',
    String(cur > 0 ? cur : 0)
  )
  if (input === null) return
  const days = parseInt(input, 10)
  if (isNaN(days) || days < 0) {
    alert('请输入非负整数天数')
    return
  }
  api.setAdminUserExpiry(u.id, days)
    .then(() => {
      u.expires_at = days > 0 ? Math.floor(Date.now() / 1000) + days * 86400 : 0
      alert(u.username + ' 有效期已更新')
    })
    .catch(e => alert('设置失败: ' + (e.message || e)))
}

/** 用户权限位列表 */
function uPerms(u) {
  return Array.isArray(u.perms) ? u.perms : []
}

/** 加载用户列表 */
async function loadUsers() {
  try {
    const res = await api.fetchAdminUsers()
    users.value = res.users || []
    allPerms.value = res.perms || []
  } catch (e) {
    alert('加载用户失败: ' + (e.message || e))
  }
}

/** 创建账号 */
async function createUser() {
  if (!newUser.value.username || !newUser.value.password) {
    createMsg.value = '用户名和密码必填'
    createMsgType.value = 'err'
    return
  }
  creating.value = true
  createMsg.value = ''
  try {
    await api.createAdminUser({
      username: newUser.value.username,
      password: newUser.value.password,
      role: newUser.value.role,
      perms: newUser.value.perms,
      expires_days: newUser.value.permanent ? 0 : (newUser.value.expiresDays || 0),
    })
    createMsg.value = '账号已创建'
    createMsgType.value = 'ok'
    newUser.value = { username: '', password: '', role: 'user', perms: [], expiresDays: 0, permanent: true }
    loadUsers()
  } catch (e) {
    createMsg.value = '创建失败: ' + (e.message || e)
    createMsgType.value = 'err'
  }
  creating.value = false
}

/** 切换角色 */
async function toggleRole(u) {
  const role = u.role === 'admin' ? 'user' : 'admin'
  try {
    await api.setAdminUserRole(u.id, role)
    u.role = role
  } catch (e) {
    alert('操作失败: ' + (e.message || e))
  }
}

/** 切换权限位 */
async function togglePerm(u, p, ev) {
  const next = ev.target.checked
    ? [...uPerms(u), p]
    : uPerms(u).filter(x => x !== p)
  try {
    await api.setAdminUserPerms(u.id, next)
    u.perms = next
  } catch (e) {
    alert('权限更新失败: ' + (e.message || e))
    ev.target.checked = !ev.target.checked
  }
}

/** 重置密码 */
function askResetPassword(u) {
  const pw = prompt('为 ' + u.username + ' 设置新密码（留空取消）')
  if (!pw) return
  api.setAdminUserPassword(u.id, pw)
    .then(() => alert(u.username + ' 密码已重置'))
    .catch(e => alert('重置失败: ' + (e.message || e)))
}

/** 启用/禁用 */
async function toggleEnabled(u) {
  try {
    await api.setAdminUserEnabled(u.id, !u.enabled)
    u.enabled = !u.enabled
  } catch (e) {
    alert('操作失败: ' + (e.message || e))
  }
}

/** 删除用户（二次确认） */
function askDeleteUser(u) {
  if (!confirm('确定删除用户 ' + u.username + '？该操作不可恢复。')) return
  api.deleteAdminUser(u.id)
    .then(() => {
      users.value = users.value.filter(x => x.id !== u.id)
      alert(u.username + ' 已删除')
    })
    .catch(e => alert('删除失败: ' + (e.message || e)))
}

/** 打开战法参数配置弹层 */
async function openStrategy(u) {
  activeUser.value = u
  activeStrategy.value = { dragon: {}, double_bump: {}, n_shape: {}, dragon_return: {}, momentum: {} }
  strategyMsg.value = ''
  try {
    const sc = await api.fetchAdminStrategyConfig(u.id)
    if (sc) {
      for (const group of strategyGroups) {
        const src = sc[group.key]
        if (src) Object.assign(activeStrategy.value[group.key], src)
      }
    }
  } catch (e) {
    strategyMsg.value = '读取配置失败: ' + (e.message || e)
    strategyMsgType.value = 'err'
  }
}

function closeStrategy() {
  activeUser.value = null
}

/** 保存代配战法参数 */
async function saveStrategy() {
  strategySaving.value = true
  strategyMsg.value = ''
  try {
    await api.setAdminStrategyConfig(activeUser.value.id, activeStrategy.value)
    strategyMsg.value = '已保存，该账号热更新即时生效'
    strategyMsgType.value = 'ok'
  } catch (e) {
    strategyMsg.value = '保存失败: ' + (e.message || e)
    strategyMsgType.value = 'err'
  }
  strategySaving.value = false
}

onMounted(loadUsers)
</script>

<style scoped>
.admin-page { max-width: 900px; }
.admin-page h2 { font-size: 18px; font-weight: 600; margin-bottom: 16px; }
.card { background: #1a1a2e; border-radius: 8px; padding: 16px; margin-bottom: 12px; }
.card-header { font-size: 14px; font-weight: 600; color: #ccc; margin-bottom: 12px; }
.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px 16px; margin-bottom: 12px; }
.form-row { display: flex; flex-direction: column; gap: 4px; font-size: 13px; }
.form-row label { color: #888; }
.form-row input, .form-row select {
  padding: 6px 10px; border-radius: 4px; border: 1px solid #333;
  background: #0f0f23; color: #e0e0e0; font-size: 14px; outline: none;
}
.form-row input:focus, .form-row select:focus { border-color: #FF4D4F; }
.perm-checks { display: flex; flex-wrap: wrap; gap: 6px 14px; padding: 4px 0; }
.perm-check { display: inline-flex; align-items: center; gap: 4px; font-size: 13px; color: #aaa; cursor: pointer; }
.perm-check input { accent-color: #FF4D4F; }
.expiry-row { display: flex; align-items: center; gap: 12px; }
.expiry-row input[type="number"] {
  width: 90px; padding: 6px 10px; border-radius: 4px; border: 1px solid #333;
  background: #0f0f23; color: #e0e0e0; font-size: 14px; outline: none;
}
.field-hint { font-size: 12px; color: #666; }

.btn-primary {
  padding: 6px 16px; border-radius: 4px; border: 1px solid #FF4D4F;
  background: transparent; color: #FF4D4F; cursor: pointer; font-size: 14px;
}
.btn-primary:hover { background: rgba(255,77,79,0.1); }
.btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }

.user-table { display: flex; flex-direction: column; gap: 10px; }
.user-row {
  display: flex; align-items: center; justify-content: space-between; gap: 12px;
  padding: 10px 12px; border: 1px solid #2a2a3e; border-radius: 6px;
}
.user-main { flex: 1; min-width: 0; }
.user-name { font-size: 15px; font-weight: 600; color: #e0e0e0; display: flex; align-items: center; gap: 8px; }
.role-tag { font-size: 12px; padding: 1px 8px; border-radius: 4px; }
.role-admin { background: rgba(76,175,80,0.15); color: #4caf50; }
.role-user { background: rgba(100,181,246,0.12); color: #64b5f6; }
.role-disabled { background: rgba(255,77,79,0.15); color: #FF4D4F; }
.user-meta { font-size: 12px; color: #666; margin: 4px 0 6px; }
.user-actions { display: flex; flex-wrap: wrap; gap: 6px; }
.btn-mini {
  padding: 4px 10px; border-radius: 4px; border: 1px solid #333;
  background: transparent; color: #bbb; cursor: pointer; font-size: 12px;
}
.btn-mini:hover { background: #2a2a3e; color: #e0e0e0; }
.btn-mini:disabled { opacity: 0.4; cursor: not-allowed; }
.btn-mini.btn-danger { border-color: #6b2b2b; color: #ff7a7a; }
.btn-mini.btn-danger:hover { background: rgba(255,77,79,0.15); color: #ff9a9a; }
.btn-mini.btn-danger:disabled { opacity: 0.4; }

.feedback { font-size: 13px; margin-left: 10px; }
.feedback.ok { color: #4caf50; }
.feedback.err { color: #FF4D4F; }

.modal-mask {
  position: fixed; inset: 0; background: rgba(0,0,0,0.6);
  display: flex; align-items: center; justify-content: center; z-index: 100;
}
.modal {
  background: #14142a; border-radius: 10px; padding: 18px; width: 92%; max-width: 560px;
  max-height: 86vh; overflow-y: auto; border: 1px solid #2a2a3e;
}
.modal-header { display: flex; align-items: center; justify-content: space-between; font-size: 15px; font-weight: 600; color: #e0e0e0; margin-bottom: 12px; }
.btn-close { background: none; border: none; color: #888; font-size: 16px; cursor: pointer; }
.strategy-groups { display: flex; flex-direction: column; gap: 10px; }
.group-card { padding: 12px; }
.modal-footer { margin-top: 14px; display: flex; align-items: center; gap: 10px; }

.switch { position: relative; display: inline-block; width: 44px; height: 24px; }
.switch input { opacity: 0; width: 0; height: 0; }
.slider {
  position: absolute; cursor: pointer; inset: 0; border-radius: 24px;
  background: #333; transition: 0.3s;
}
.slider::before {
  content: ''; position: absolute; height: 18px; width: 18px; left: 3px; top: 3px;
  border-radius: 50%; background: #888; transition: 0.3s;
}
.switch input:checked + .slider { background: #FF4D4F; }
.switch input:checked + .slider::before { transform: translateX(20px); background: #fff; }

@media (max-width: 768px) {
  .form-grid { grid-template-columns: 1fr; }
  .user-row { flex-direction: column; align-items: flex-start; }
}
</style>

// web/src/pages/Admin.jsx
// ── 用户管理页 Admin.jsx（仅 admin 可见）──
// Admin page (admin only): account creation, role/perm config, password reset,
// enable/disable, expiry, and per-account strategy param delegation.
import React, { useState, useEffect } from 'react'
import {
  Button, Switch, Input, InputNumber, Select, Dialog, DialogPlugin,
  Table, Tag, Card, Form, Checkbox,
} from 'tdesign-react'
import * as api from '../api/index.js'
import { showToast } from '../ui.jsx'

const PERM_LABELS = { research_approve: '研究审批' }

// 战法参数分组定义（与 Vue 版 Settings/Admin 一致）
const strategyGroups = [
  {
    key: 'dragon', title: '龙头战法（权重合计≤1）',
    fields: [
      { k: 'f1_seal_weight', label: 'F1 首封权重', step: 0.05 },
      { k: 'f2_resonance_weight', label: 'F2 共振权重', step: 0.05 },
      { k: 'f3_premium_weight', label: 'F3 溢价权重', step: 0.05 },
      { k: 'f4_rs_weight', label: 'F4 强度权重', step: 0.05 },
      { k: 'pullback_max_pct', label: '最大回撤%', step: 0.01 },
      { k: 'breaker_sell_half_pct', label: '炸板减半%', step: 0.01 },
      { k: 'breaker_sell_all_pct', label: '炸板清仓%', step: 0.01 },
      { k: 'buy_pullback_sell_half_pct', label: '买入回撤减半%', step: 0.01 },
      { k: 'buy_pullback_sell_all_pct', label: '买入回撤清仓%', step: 0.01 },
      { k: 'buy_day_close_below', label: '买入日收盘低于%', step: 0.01 },
      { k: 'next_open_if_below', label: '次日开盘低于%', step: 0.01 },
      { k: 'take_profit_pct', label: '止盈%', step: 1 },
    ],
  },
  {
    key: 'double_bump', title: '双响炮战法',
    fields: [
      { k: 'first_break_volume_multiple', label: '一突量比', step: 0.1 },
      { k: 'second_break_volume_multiple', label: '二突量比', step: 0.1 },
      { k: 'adjust_vol_ratio_max', label: '调整量比上限', step: 0.5 },
      { k: 'position_weight', label: '调整深度权重', step: 0.05 },
      { k: 'ma_weight', label: '均线权重', step: 0.05 },
      { k: 'volume_weight', label: '量能权重', step: 0.05 },
      { k: 'double_bump_take_profit_pct', label: '止盈%', step: 0.01 },
    ],
  },
  {
    key: 'n_shape', title: 'N 形战法',
    fields: [
      { k: 'n_pattern_score_threshold', label: 'N 形态分阈值', step: 1 },
      { k: 'hard_stop_loss', label: '硬止损%', step: 0.01 },
    ],
  },
  {
    key: 'dragon_return', title: '龙回头战法',
    fields: [
      { k: 'stop_loss_pct', label: '止损%', step: 0.01 },
      { k: 'take_profit_pct', label: '止盈%', step: 0.01 },
      { k: 'max_hold_days', label: '最长持仓天数', step: 1 },
      { k: 'target1_multiplier', label: '目标1倍数', step: 0.05 },
      { k: 'target2_multiplier', label: '目标2倍数', step: 0.05 },
      { k: 'trailing_drawback', label: '移动止损回撤%', step: 0.01 },
    ],
  },
  {
    key: 'momentum', title: '动量分权重（合计建议=100）',
    fields: [
      { k: 'volume_price_weight', label: '量价权重', step: 5 },
      { k: 'macd_weight', label: 'MACD权重', step: 5 },
      { k: 'trend_weight', label: '走势权重', step: 5 },
      { k: 'momentum_gate_enabled', label: '动量提升才提醒', type: 'switch', hint: '开启后仅当动量分提升(或回落≤容忍差)才放行 双响炮/龙头/龙回头 战法信号；N形不受影响' },
      { k: 'momentum_delta_tol', label: '回落容忍差(分)', step: 1, hint: '动量分相对上一轮回落 ≤ 该值仍视为提升；设为0表示需严格不回落' },
    ],
  },
]

// 将权限标识翻译为中文
function permLabel(p) {
  return PERM_LABELS[p] || p
}

// 时间戳格式化为 YYYY-MM-DD
function fmtTime(ts) {
  if (!ts) return '-'
  const d = new Date(ts * 1000)
  const p = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`
}

// 根据用户有效期生成中文说明
function expiryText(u) {
  if (!u.expires_at) return '有效期：永久'
  const now = Date.now()
  const exp = u.expires_at * 1000
  if (exp < now) return '有效期：已到期'
  const days = Math.ceil((exp - now) / 86400000)
  return '有效期：' + fmtTime(u.expires_at) + '（剩 ' + days + ' 天）'
}

// 封装 tdesign 确认对话框为 Promise
function confirmDialog(body, header = '确认') {
  return new Promise((resolve) => {
    const d = DialogPlugin.confirm({
      header,
      body,
      theme: 'warning',
      onConfirm: () => { d.hide(); resolve(true) },
      onClose: () => { d.hide(); resolve(false) },
    })
  })
}

/**
 * 用户管理页面组件（仅 admin 可见）
 * 负责账号创建、角色/权限/有效期管理、密码重置与战法参数下发。
 * @returns {JSX.Element}
 */
export default function Admin() {
  const [users, setUsers] = useState([])
  const [allPerms, setAllPerms] = useState([])
  const [creating, setCreating] = useState(false)
  const [createMsg, setCreateMsg] = useState('')
  const [createMsgType, setCreateMsgType] = useState('ok')
  const [newUser, setNewUser] = useState({ username: '', password: '', role: 'user', perms: [], expiresDays: 0, permanent: true })

  const [activeUser, setActiveUser] = useState(null)
  const [activeStrategy, setActiveStrategy] = useState({})
  const [strategySaving, setStrategySaving] = useState(false)
  const [strategyMsg, setStrategyMsg] = useState('')
  const [strategyMsgType, setStrategyMsgType] = useState('ok')

  // 重置密码弹窗状态
  const [pwUser, setPwUser] = useState(null)
  const [pwValue, setPwValue] = useState('')
  // 设置有效期弹窗状态
  const [expUser, setExpUser] = useState(null)
  const [expDays, setExpDays] = useState(0)

  // 安全读取用户权限数组
  function uPerms(u) {
    return Array.isArray(u.perms) ? u.perms : []
  }

  // 加载全部用户与权限列表
  async function loadUsers() {
    try {
      const res = await api.fetchAdminUsers()
      setUsers(res.users || [])
      setAllPerms(res.perms || [])
    } catch (e) {
      showToast('加载用户失败: ' + (e.message || e), 'error')
    }
  }

  // 创建新账号并清空表单
  function createUser() {
    if (!newUser.username || !newUser.password) {
      setCreateMsg('用户名和密码必填'); setCreateMsgType('err'); return
    }
    setCreating(true); setCreateMsg('')
    api.createAdminUser({
      username: newUser.username,
      password: newUser.password,
      role: newUser.role,
      perms: newUser.perms,
      expires_days: newUser.permanent ? 0 : (newUser.expiresDays || 0),
    }).then(() => {
      setCreateMsg('账号已创建'); setCreateMsgType('ok')
      setNewUser({ username: '', password: '', role: 'user', perms: [], expiresDays: 0, permanent: true })
      loadUsers()
    }).catch((e) => {
      setCreateMsg('创建失败: ' + (e.message || e)); setCreateMsgType('err')
    }).finally(() => setCreating(false))
  }

  // 切换用户 admin/user 角色
  async function toggleRole(u) {
    const role = u.role === 'admin' ? 'user' : 'admin'
    try {
      await api.setAdminUserRole(u.id, role)
      setUsers(users.map((x) => x.id === u.id ? { ...x, role } : x))
    } catch (e) {
      showToast('操作失败: ' + (e.message || e), 'error')
    }
  }

  // 全量更新某用户权限位
  async function setUserPerms(u, next) {
    try {
      await api.setAdminUserPerms(u.id, next)
      setUsers(users.map((x) => x.id === u.id ? { ...x, perms: next } : x))
    } catch (e) {
      showToast('权限更新失败: ' + (e.message || e), 'error')
    }
  }

  // 勾选/取消勾选用户权限
  function togglePerm(u, val) {
    setUserPerms(u, val)
  }

  // 提交重置密码
  function doResetPassword() {
    if (!pwValue) { showToast('密码不能为空', 'warning'); return }
    api.setAdminUserPassword(pwUser.id, pwValue)
      .then(() => { showToast(pwUser.username + ' 密码已重置', 'success'); setPwUser(null) })
      .catch((e) => showToast('重置失败: ' + (e.message || e), 'error'))
  }

  // 启用/禁用账号
  async function toggleEnabled(u) {
    try {
      await api.setAdminUserEnabled(u.id, !u.enabled)
      setUsers(users.map((x) => x.id === u.id ? { ...x, enabled: !x.enabled } : x))
    } catch (e) {
      showToast('操作失败: ' + (e.message || e), 'error')
    }
  }

  // 打开设置有效期弹窗
  function askSetExpiry(u) {
    const cur = u.expires_at ? Math.ceil((u.expires_at * 1000 - Date.now()) / 86400000) : 0
    setExpUser(u)
    setExpDays(cur > 0 ? cur : 0)
  }

  // 提交设置有效期
  function doSetExpiry() {
    if (isNaN(expDays) || expDays < 0) { showToast('请输入非负整数天数', 'warning'); return }
    const days = expDays || 0
    api.setAdminUserExpiry(expUser.id, days)
      .then(() => {
        setUsers(users.map((x) => x.id === expUser.id ? { ...x, expires_at: days > 0 ? Math.floor(Date.now() / 1000) + days * 86400 : 0 } : x))
        showToast(expUser.username + ' 有效期已更新', 'success')
        setExpUser(null)
      })
      .catch((e) => showToast('设置失败: ' + (e.message || e), 'error'))
  }

  // 确认并删除用户
  function askDeleteUser(u) {
    confirmDialog('确定删除用户 ' + u.username + '？该操作不可恢复。', '删除用户').then((ok) => {
      if (!ok) return
      api.deleteAdminUser(u.id)
        .then(() => { setUsers(users.filter((x) => x.id !== u.id)); showToast(u.username + ' 已删除', 'success') })
        .catch((e) => showToast('删除失败: ' + (e.message || e), 'error'))
    })
  }

  // 打开指定用户的战法参数配置弹窗并加载其专属配置
  async function openStrategy(u) {
    setActiveUser(u)
    setActiveStrategy({ dragon: {}, double_bump: {}, n_shape: {}, dragon_return: {}, momentum: {} })
    setStrategyMsg('')
    try {
      const sc = await api.fetchAdminStrategyConfig(u.id)
      if (sc) {
        const next = { dragon: {}, double_bump: {}, n_shape: {}, dragon_return: {}, momentum: {} }
        for (const group of strategyGroups) {
          const src = sc[group.key]
          if (src) Object.assign(next[group.key], src)
        }
        setActiveStrategy(next)
      }
    } catch (e) {
      setStrategyMsg('读取配置失败: ' + (e.message || e)); setStrategyMsgType('err')
    }
  }

  function closeStrategy() { setActiveUser(null) }

  // 保存当前选中用户的战法参数下发配置
  async function saveStrategy() {
    if (!activeUser) return
    setStrategySaving(true); setStrategyMsg('')
    try {
      await api.setAdminStrategyConfig(activeUser.id, activeStrategy)
      setStrategyMsg('已保存，该账号热更新即时生效'); setStrategyMsgType('ok')
    } catch (e) {
      setStrategyMsg('保存失败: ' + (e.message || e)); setStrategyMsgType('err')
    }
    setStrategySaving(false)
  }

  // 用户列表列定义
  const userColumns = [
    {
      colKey: 'user', title: '用户', width: 220,
      cell: ({ row }) => (
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 15, fontWeight: 600 }}>{row.username}</span>
            <Tag theme={row.role === 'admin' ? 'success' : 'primary'} variant="light">
              {row.role === 'admin' ? '管理员' : '用户'}
            </Tag>
            {!row.enabled && <Tag theme="danger" variant="light">已禁用</Tag>}
          </div>
          <div style={{ fontSize: 12, color: '#888', marginTop: 4 }}>
            ID: {row.id} · 创建于 {fmtTime(row.created_at)} · {expiryText(row)}
          </div>
        </div>
      ),
    },
    {
      colKey: 'perms', title: '权限', width: 220,
      cell: ({ row }) => (
        <Checkbox.Group
          value={uPerms(row)}
          disabled={row.role === 'admin'}
          onChange={(val) => togglePerm(row, val)}
        >
          {allPerms.map((p) => (
            <Checkbox key={p} value={p}>{permLabel(p)}</Checkbox>
          ))}
        </Checkbox.Group>
      ),
    },
    {
      colKey: 'ops', title: '操作', width: 360,
      cell: ({ row }) => (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
          <Button size="small" theme="default" onClick={() => toggleRole(row)}>
            {row.role === 'admin' ? '降为普通用户' : '设为管理员'}
          </Button>
          <Button size="small" theme="default" onClick={() => { setPwUser(row); setPwValue('') }}>重置密码</Button>
          <Button size="small" theme="default" disabled={row.role === 'admin'} onClick={() => toggleEnabled(row)}>
            {row.enabled ? '禁用' : '启用'}
          </Button>
          <Button size="small" theme="default" disabled={row.role === 'admin'} onClick={() => askSetExpiry(row)}>设置有效期</Button>
          <Button size="small" theme="primary" onClick={() => openStrategy(row)}>配战法参数</Button>
          <Button size="small" theme="danger" disabled={row.role === 'admin'} onClick={() => askDeleteUser(row)}>删除</Button>
        </div>
      ),
    },
  ]

  useEffect(() => { loadUsers() }, [])

  return (
    <div>
      <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 16 }}>用户管理</h2>

      <Card title="开通新账号" style={{ marginBottom: 12 }}>
        <Form layout="vertical">
          <Form.FormItem label="用户名">
            <Input value={newUser.username} onChange={(v) => setNewUser({ ...newUser, username: v })} placeholder="登录名" />
          </Form.FormItem>
          <Form.FormItem label="初始密码">
            <Input type="password" value={newUser.password} onChange={(v) => setNewUser({ ...newUser, password: v })} placeholder="首次登录用" />
          </Form.FormItem>
          <Form.FormItem label="角色">
            <Select value={newUser.role} onChange={(v) => setNewUser({ ...newUser, role: v })} style={{ width: 200 }}>
              <Select.Option value="user">普通用户</Select.Option>
              <Select.Option value="admin">管理员</Select.Option>
            </Select>
          </Form.FormItem>
          <Form.FormItem label="权限">
            <Checkbox.Group value={newUser.perms} onChange={(val) => setNewUser({ ...newUser, perms: val })}>
              {allPerms.map((p) => (
                <Checkbox key={p} value={p}>{permLabel(p)}</Checkbox>
              ))}
            </Checkbox.Group>
          </Form.FormItem>
          <Form.FormItem label="有效期">
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <InputNumber
                value={newUser.expiresDays}
                min={0}
                disabled={newUser.permanent}
                onChange={(v) => setNewUser({ ...newUser, expiresDays: v || 0 })}
                placeholder="天数"
                style={{ width: 140 }}
              />
              <Switch value={newUser.permanent} onChange={(v) => setNewUser({ ...newUser, permanent: v })} />
              <span style={{ fontSize: 13, color: '#888' }}>永久</span>
            </div>
            <span style={{ fontSize: 12, color: '#888' }}>填天数表示到期后自动失效；开启"永久"则不过期</span>
          </Form.FormItem>
        </Form>
        <Button theme="primary" loading={creating} onClick={createUser}>
          {creating ? '创建中...' : '创建账号'}
        </Button>
        {createMsg && (
          <span style={{ marginLeft: 10, fontSize: 13, color: createMsgType === 'ok' ? '#00a870' : '#e34d59' }}>{createMsg}</span>
        )}
      </Card>

      <Card title="账号列表" style={{ marginBottom: 12 }}>
        <Table
          rowKey="id"
          data={users}
          columns={userColumns}
          bordered={false}
          size="medium"
          pagination={{ defaultPageSize: 10, showJumper: true }}
        />
      </Card>

      {/* 重置密码弹窗 */}
      <Dialog
        visible={!!pwUser}
        header={pwUser ? '为 ' + pwUser.username + ' 重置密码' : '重置密码'}
        onClose={() => setPwUser(null)}
        onConfirm={doResetPassword}
        confirmBtn="确定重置"
      >
        <Input type="password" value={pwValue} onChange={(v) => setPwValue(v)} placeholder="输入新密码（留空取消）" />
      </Dialog>

      {/* 设置有效期弹窗 */}
      <Dialog
        visible={!!expUser}
        header={expUser ? '为 ' + expUser.username + ' 设置有效期' : '设置有效期'}
        onClose={() => setExpUser(null)}
        onConfirm={doSetExpiry}
        confirmBtn="确定"
      >
        <div style={{ marginBottom: 8, fontSize: 13, color: '#888' }}>
          输入天数（0 表示永久）{expUser && expUser.expires_at ? '；当前剩余约 ' + (expUser.expires_at ? Math.ceil((expUser.expires_at * 1000 - Date.now()) / 86400000) : 0) + ' 天' : '；当前永久'}
        </div>
        <InputNumber value={expDays} min={0} onChange={(v) => setExpDays(v || 0)} style={{ width: 200 }} />
      </Dialog>

      {/* 代配战法参数弹窗 */}
      <Dialog
        visible={!!activeUser}
        header={activeUser ? '为 ' + activeUser.username + ' 配置战法参数' : '配置战法参数'}
        onClose={closeStrategy}
        onConfirm={saveStrategy}
        confirmBtn={strategySaving ? '保存中...' : '保存该账号战法参数'}
        width={560}
        footer={strategySaving ? null : undefined}
      >
        {strategyGroups.map((group) => (
          <Card key={group.key} title={group.title} style={{ marginBottom: 10 }}>
            {group.fields.map((f) => (
              <Form.FormItem key={f.k} label={f.label} style={{ marginBottom: 8 }}>
                {f.type === 'switch' ? (
                  <Switch
                    value={!!(activeStrategy[group.key] && activeStrategy[group.key][f.k])}
                    onChange={(v) => setActiveStrategy({
                      ...activeStrategy,
                      [group.key]: { ...activeStrategy[group.key], [f.k]: v },
                    })}
                  />
                ) : (
                  <InputNumber
                    step={f.step || 'any'}
                    value={(activeStrategy[group.key] && activeStrategy[group.key][f.k]) ?? ''}
                    onChange={(v) => setActiveStrategy({
                      ...activeStrategy,
                      [group.key]: { ...activeStrategy[group.key], [f.k]: v },
                    })}
                    placeholder="0"
                    style={{ width: 200 }}
                  />
                )}
              </Form.FormItem>
            ))}
          </Card>
        ))}
        {strategyMsg && (
          <span style={{ fontSize: 13, color: strategyMsgType === 'ok' ? '#00a870' : '#e34d59' }}>{strategyMsg}</span>
        )}
      </Dialog>
    </div>
  )
}
