// web/src/pages/Hotspot.jsx
// ── 热点页面 Hotspot.jsx ──
// 展示热点板块（含异动原因弹窗）、全市场个股评分排名、宏观日历、IPO日历、热点资讯。
// 全面使用 TDesign 组件：Card / Table / Dialog / Tag / Button，纯内联样式，无自定义 CSS。
import React, { useState, useEffect, useRef, useMemo } from 'react'
import { Card, Table, Dialog, Tag, Button, MessagePlugin } from 'tdesign-react'
import * as api from '../api/index.js'
import { fetchSignalLogs, fetchStageRecords } from '../api/index.js'

// ── 工具函数 ──
// 截断异动原因为简短描述
function shortReason(r) {
  if (!r) return ''
  const idx = r.indexOf('，')
  return idx > 0 ? r.slice(0, idx) : r.slice(0, 18)
}

// 根据分数与阈值返回评分单元格颜色（红强 / 橙达标 / 灰偏低）
function scoreColorF(score, pass, strongMin) {
  if (!score || score <= 0) return '#555'
  if (score >= strongMin) return '#e34d59'
  if (pass) return '#FAAD14'
  return '#555'
}

// 安全读取字段值
function val(e, key) {
  const v = e[key]
  if (typeof v === 'string') return v || ''
  return v || 0
}

/**
 * 热点页面组件
 * 展示热点板块、全市场个股评分排名、宏观日历、IPO 日历与热点资讯。
 * @returns {JSX.Element}
 */
export default function Hotspot() {
  const [sectors, setSectors] = useState([])
  const [evals, setEvals] = useState([])
  const [news, setNews] = useState([])
  const [ipoCalendar, setIpoCalendar] = useState([])
  const [reasonTarget, setReasonTarget] = useState(null)
  const [showLog, setShowLog] = useState(false)
  const [logSignal, setLogSignal] = useState('')
  const [logStage, setLogStage] = useState('')
  const [reanalyzing, setReanalyzing] = useState(false)

  const [sortKey, setSortKey] = useState('')
  const [sortDir, setSortDir] = useState(-1)

  const loadingRef = useRef(false)
  const timerRef = useRef(null)
  const unsubSSERef = useRef(null)
  const visHandlerRef = useRef(null)

  // 用 ref 保存最新评分数据，避免轮询闭包引用旧值
  const evalsRef = useRef([])
  useEffect(() => { evalsRef.current = evals }, [evals])

  // 切换排序键或方向
  function setSort(key) {
    if (sortKey === key) setSortDir((d) => d * -1)
    else { setSortKey(key); setSortDir(-1) }
  }

  // 过滤非日历类资讯
  const newsItems = useMemo(() => news.filter((n) => n.source !== '宏观日历' && n.source !== '政策反制'), [news])
  // 过滤宏观日历与政策反制事件
  const calendarEvents = useMemo(() => news.filter((n) => n.source === '宏观日历' || n.source === '政策反制'), [news])

  // 根据上市日期计算 IPO 倒计时
  function ipoCountdown(c) {
    const ds = c.listing_date || c.ipo_date
    if (!ds) return c.list_status === 'L' ? '已上市' : '即将上市'
    const t = new Date(+ds.slice(0, 4), +ds.slice(4, 6) - 1, +ds.slice(6, 8))
    const diff = Math.ceil((t - Date.now()) / 86400000)
    if (diff > 0) return `${diff}天后`
    if (diff === 0) return '📌今天'
    return `${-diff}天前`
  }

  // 将时间戳或字符串统一格式化为 MM-DD HH:mm
  function fmtNewsTime(dt) {
    if (dt === null || dt === undefined || dt === '') return ''
    const s = String(dt)
    if (/^\d+$/.test(s)) {
      const t = new Date(Number(s) * 1000)
      if (!isNaN(t.getTime())) {
        const mm = String(t.getMonth() + 1).padStart(2, '0')
        const dd = String(t.getDate()).padStart(2, '0')
        const hh = String(t.getHours()).padStart(2, '0')
        const mi = String(t.getMinutes()).padStart(2, '0')
        return `${mm}-${dd} ${hh}:${mi}`
      }
      return ''
    }
    return s.length >= 16 ? s.slice(5, 16) : s
  }

  // 按排序键计算展示列表，默认按最高维度分倒序
  const sortedEvals = useMemo(() => {
    if (!evals || !evals.length) return []
    const arr = [...evals]
    const sk = sortKey
    if (!sk) {
      return arr.sort((a, b) => {
        const sa = Math.max(a.n_score || 0, a.dragon_score || 0, a.db_score || 0, a.dr_score || 0, a.m_score || 0)
        const sb = Math.max(b.n_score || 0, b.dragon_score || 0, b.db_score || 0, b.dr_score || 0, b.m_score || 0)
        return sb - sa
      })
    }
    const dir = sortDir
    return arr.sort((a, b) => {
      const va = val(a, sk)
      const vb = val(b, sk)
      if (typeof va === 'string') return va.localeCompare(vb) * dir
      return (va - vb) * dir
    })
  }, [evals, sortKey, sortDir])

  // 加载热点板块、个股评分、新闻与 IPO 日历
  async function load() {
    if (loadingRef.current) return
    loadingRef.current = true
    try {
      try {
        const st = await api.fetchStatus()
        api.setLastSession(st.session)
        if (api.isTradingSession(st.session) || !evalsRef.current.length) {
          try {
            const e = await api.fetchEvaluations()
            if (e) setEvals(e)
          } catch (_) {}
        }
      } catch (_) {}
      let fromRecords = false
      try {
        const recs = await api.fetchSectorHotRecords()
        if (Array.isArray(recs) && recs.length) {
          setSectors(recs[0].sectors || [])
          fromRecords = true
        }
      } catch (_) {}
      if (!fromRecords) {
        try {
          const s = await api.fetchSectorHot()
          if (s) setSectors(s)
        } catch (_) {}
      }
      try {
        const n = await api.fetchNews(true)
        if (n) setNews(n)
      } catch (_) {}
      try {
        const ipo = await api.fetchIPOCalendar()
        if (ipo) setIpoCalendar(ipo)
      } catch (_) {}
    } finally {
      loadingRef.current = false
    }
  }

  // SSE 推送到达时刷新热点数据
  function handleSSE() { load() }

  // 触发新闻重新分析
  async function onReanalyze() {
    if (reanalyzing) return
    setReanalyzing(true)
    try {
      const res = await api.reanalyzeNews()
      if (res && res.accepted !== false) {
        setTimeout(() => load(), 1500)
      }
    } catch (_) {} finally {
      setReanalyzing(false)
    }
  }

  // 打开日志弹窗并加载信号与 Stage 日志
  async function openLog() {
    setShowLog(true)
    try {
      const sl = await fetchSignalLogs()
      setLogSignal(typeof sl === 'string' ? sl : JSON.stringify(sl, null, 2))
    } catch (_) { setLogSignal('') }
    try {
      const st = await fetchStageRecords()
      setLogStage(typeof st === 'string' ? st : JSON.stringify(st, null, 2))
    } catch (_) { setLogStage('') }
  }

  // 挂载时加载数据、启动轮询与 SSE；处理页面可见性变化；卸载时清理
  useEffect(() => {
    load()
    timerRef.current = setInterval(load, 5000)
    visHandlerRef.current = () => {
      if (document.hidden) {
        if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null }
      } else {
        if (!timerRef.current) {
          load()
          timerRef.current = setInterval(load, 5000)
        }
      }
    }
    document.addEventListener('visibilitychange', visHandlerRef.current)
    api.connectSSE()
    unsubSSERef.current = api.onSSE(handleSSE)
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
      if (visHandlerRef.current) document.removeEventListener('visibilitychange', visHandlerRef.current)
      if (unsubSSERef.current) { unsubSSERef.current(); unsubSSERef.current = null }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // 板块卡片网格列
  const sectorColumns = [
    { colKey: 'name', title: '板块', width: 120 },
    { colKey: 'reason', title: '异动原因', width: 200, ellipsis: true, cell: ({ row }) => row.reason ? <span style={{ color: '#4fc3f7' }}>{shortReason(row.reason)}</span> : null },
    { colKey: 'score', title: '评分', width: 80, cell: ({ row }) => <span style={{ color: '#FAAD14' }}>{Math.round((row.score || 0) * 100)}分</span> },
    { colKey: 'change_pct', title: '涨幅', width: 90, cell: ({ row }) => <span style={{ color: (row.change_pct || 0) >= 0 ? '#e34d59' : '#00a870', fontWeight: 700 }}>{(row.change_pct || 0) > 0 ? '+' : ''}{(row.change_pct || 0).toFixed(2)}%</span> },
    { colKey: 'meta', title: '涨停/流入', width: 180, cell: ({ row }) => (
      <span style={{ color: '#666', fontSize: 13 }}>
        {row.d1 > 0 && <Tag size="small" style={{ marginRight: 6 }}>D1 {row.d1.toFixed(0)}</Tag>}
        <span>涨停 {row.limitup_cnt || 0}</span>
        <span style={{ marginLeft: 8 }}>流入 {row.net_inflow ? (row.net_inflow / 1e8).toFixed(1) + '亿' : '—'}</span>
      </span>
    ) },
  ]

  // 个股评分排名列
  const evalColumns = [
    { colKey: 'code', title: '代码', width: 90, sorter: (a, b) => (a.code || '').localeCompare(b.code || ''), cell: ({ row }) => <span style={{ color: '#4fc3f7', fontFamily: 'monospace' }}>{row.code}</span> },
    { colKey: 'name', title: '名称', width: 90, sorter: (a, b) => (a.name || '').localeCompare(b.name || ''), cell: ({ row }) => <span style={{ color: '#ccc' }}>{row.name || '-'}</span> },
    { colKey: 'price', title: '现价', width: 90, sorter: (a, b) => (a.price || 0) - (b.price || 0), cell: ({ row }) => '¥' + (row.price || 0).toFixed(2) },
    { colKey: 'change_pct', title: '涨跌', width: 100, sorter: (a, b) => (a.change_pct || 0) - (b.change_pct || 0), cell: ({ row }) => <span style={{ color: (row.change_pct || 0) >= 0 ? '#e34d59' : '#00a870', fontWeight: 600 }}>{(row.change_pct || 0) > 0 ? '+' : ''}{(row.change_pct || 0).toFixed(2)}%</span> },
    { colKey: 'n_score', title: 'N≥60', width: 70, sorter: (a, b) => (a.n_score || 0) - (b.n_score || 0), cell: ({ row }) => <span style={{ color: scoreColorF(row.n_score, row.n_score >= 60, 80), fontWeight: 600 }}>{row.n_score > 0 ? row.n_score.toFixed(0) : '—'}</span> },
    { colKey: 'dragon_score', title: '龙≥60', width: 70, sorter: (a, b) => (a.dragon_score || 0) - (b.dragon_score || 0), cell: ({ row }) => <span style={{ color: scoreColorF(row.dragon_score, row.dragon_score >= 60, 80), fontWeight: 600 }}>{row.dragon_score > 0 ? row.dragon_score.toFixed(0) : '—'}</span> },
    { colKey: 'db_score', title: '凸≥60', width: 70, sorter: (a, b) => (a.db_score || 0) - (b.db_score || 0), cell: ({ row }) => <span style={{ color: scoreColorF(row.db_score, row.db_score >= 60, 80), fontWeight: 600 }}>{row.db_score > 0 ? row.db_score.toFixed(0) : '—'}</span> },
    { colKey: 'dr_score', title: '回≥60', width: 70, sorter: (a, b) => (a.dr_score || 0) - (b.dr_score || 0), cell: ({ row }) => <span style={{ color: scoreColorF(row.dr_score, row.dr_score >= 60, 80), fontWeight: 600 }}>{row.dr_score > 0 ? row.dr_score.toFixed(0) : '—'}</span> },
    { colKey: 'm_score', title: '量≥50', width: 70, sorter: (a, b) => (a.m_score || 0) - (b.m_score || 0), cell: ({ row }) => <span style={{ color: scoreColorF(row.m_score, row.m_score >= 50, 70), fontWeight: 600 }}>{row.m_score > 0 ? row.m_score.toFixed(0) : '—'}</span> },
  ]

  // 宏观日历列
  const calendarColumns = [
    { colKey: 'date', title: '日期', width: 90, cell: ({ row }) => <span style={{ color: '#888' }}>{row.date}</span> },
    { colKey: 'title', title: '事件', cell: ({ row }) => <span style={{ color: '#e0e0e0' }}>{row.title}</span> },
  ]
  const calendarData = calendarEvents.map((c, i) => ({ id: 'c' + i, date: c.datetime ? c.datetime.slice(5, 10) : '', title: c.title }))

  // IPO 日历列
  const ipoColumns = [
    { colKey: 'date', title: '日期', width: 90, cell: ({ row }) => <span style={{ color: '#888' }}>{row.date}</span> },
    { colKey: 'name', title: '名称', width: 160, cell: ({ row }) => <span style={{ color: '#e0e0e0' }}>{row.name}（{row.code}）</span> },
    { colKey: 'price', title: '发行价', width: 90, cell: ({ row }) => row.issue_price ? <span style={{ color: '#4fc3f7' }}>¥{row.issue_price.toFixed(2)}</span> : null },
    { colKey: 'status', title: '状态', width: 100, cell: ({ row }) => <Tag size="small" theme={row.statusTheme}>{row.status}</Tag> },
  ]
  const ipoData = ipoCalendar.map((c, i) => ({ id: 'ipo' + i, date: c.listing_date ? c.listing_date.slice(5, 10) : (c.ipo_date ? c.ipo_date.slice(5, 10) : ''), name: c.name, code: c.code, issue_price: c.issue_price, status: ipoCountdown(c), statusTheme: c.list_status === 'L' ? 'default' : 'warning' }))

  // 资讯标签解析
  function newsTags(n) {
    const tags = []
    if (n.sentiment) { const theme = n.sentiment === '正面' ? 'success' : n.sentiment === '负面' ? 'danger' : 'default'; tags.push({ text: n.sentiment, theme }) }
    if (n.direction) { const theme = n.direction === '利好' ? 'success' : n.direction === '利空' ? 'danger' : 'default'; tags.push({ text: n.direction, theme }) }
    if (n.impact_level) { const theme = n.impact_level === '高' ? 'warning' : n.impact_level === '中' ? 'primary' : 'default'; tags.push({ text: n.impact_level + '影响', theme }) }
    return tags
  }
  // 资讯列
  const newsColumns = [
    { colKey: 'time', title: '时间', width: 100, cell: ({ row }) => <span style={{ color: '#888' }}>{row.time}</span> },
    { colKey: 'title', title: '标题', cell: ({ row }) => <span style={{ color: '#ccc' }}>{row.title}</span> },
    { colKey: 'tags', title: '标签', width: 280, cell: ({ row }) => (
      <span style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
        {row.tags.map((t, i) => <Tag key={i} size="small" theme={t.theme}>{t.text}</Tag>)}
        {(row.sectors || []).map((sec) => <Tag key={'s' + sec} size="small" theme="primary" variant="light">{sec}</Tag>)}
        {(row.stocks || []).map((stk) => <Tag key={'k' + stk} size="small" theme="warning" variant="light">{stk}</Tag>)}
      </span>
    ) },
  ]
  const newsData = newsItems.map((n, i) => ({ id: 'n' + i, time: fmtNewsTime(n.datetime), title: n.title, tags: newsTags(n), sectors: n.sectors, stocks: n.stocks }))

  return (
    <div className="page">
      <Card>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
          <span>🔥 热点板块</span>
          <Button size="small" variant="outline" theme="primary" onClick={openLog}>📋 日志</Button>
        </div>
        {sectors.length ? (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: 12 }}>
            {sectors.map((s) => (
              <Card key={s.code} bordered={false} style={{ cursor: 'pointer', background: '#12121e', border: '1px solid #2a2a3e' }} onClick={() => setReasonTarget(s)}>
                <div style={{ fontSize: 14, fontWeight: 600, color: '#e0e0e0' }}>{s.name}</div>
                {s.reason && <div style={{ fontSize: 11, color: '#888', marginTop: 4, minHeight: 28, overflow: 'hidden' }}>{shortReason(s.reason)}</div>}
                <div style={{ fontSize: 16, fontWeight: 700, color: '#FAAD14', marginTop: 4 }}>{Math.round((s.score || 0) * 100)}分</div>
                <div className={(s.change_pct || 0) >= 0 ? 'up' : 'down'} style={{ fontWeight: 700, marginTop: 2 }}>
                  {(s.change_pct || 0) > 0 ? '+' : ''}{(s.change_pct || 0).toFixed(2)}%
                </div>
                <div style={{ fontSize: 11, color: '#777', marginTop: 6 }}>
                  {(s.d1 || 0) > 0 && <span style={{ display: 'inline-block', background: 'rgba(79,195,247,0.15)', color: '#4fc3f7', borderRadius: 4, padding: '1px 5px', marginRight: 6 }}>D1 {s.d1.toFixed(0)}</span>}
                  <span>涨停 {s.limitup_cnt || 0}</span>
                  <span style={{ marginLeft: 8 }}>流入 {s.net_inflow ? (s.net_inflow / 1e8).toFixed(1) + '亿' : '—'}</span>
                </div>
              </Card>
            ))}
          </div>
        ) : (
          <div className="muted" style={{ padding: 24, textAlign: 'center' }}>暂无热点板块数据</div>
        )}
      </Card>

      {/* 板块异动原因弹窗 */}
      <Dialog visible={!!reasonTarget} header={reasonTarget ? reasonTarget.name : ''} onClose={() => setReasonTarget(null)} confirmBtn="知道了" cancelBtn="">
        {reasonTarget && (
          <div>
            <div style={{ marginBottom: 14 }}>
              <div style={{ fontWeight: 600, marginBottom: 6 }}>板块异动原因</div>
              <div style={{ fontSize: 13, color: '#ccc', whiteSpace: 'pre-wrap' }}>{reasonTarget.reason_detail || reasonTarget.reason || '暂无'}</div>
            </div>
            {reasonTarget.news_titles && reasonTarget.news_titles.length ? (
              <div>
                <div style={{ fontWeight: 600, marginBottom: 6 }}>触发新闻（{reasonTarget.news_titles.length}条）</div>
                {reasonTarget.news_titles.map((t, i) => (
                  <div key={i} style={{ display: 'flex', gap: 6, fontSize: 13, color: '#ddd', padding: '2px 0' }}>
                    <span style={{ color: '#888' }}>{i + 1}.</span>
                    <span>{t}</span>
                  </div>
                ))}
              </div>
            ) : null}
          </div>
        )}
      </Dialog>

      {/* 运行日志弹窗 */}
      <Dialog visible={showLog} header="运行日志" onClose={() => setShowLog(false)} confirmBtn="关闭" cancelBtn="">
        <div>
          <div style={{ marginBottom: 14 }}>
            <div style={{ fontWeight: 600, marginBottom: 6 }}>信号批次 / 阶段记录</div>
            <pre style={{ fontSize: 12, color: '#ccc', background: '#12121e', borderRadius: 6, padding: 10, maxHeight: 180, overflow: 'auto', margin: 0 }}>{logSignal || '暂无'}</pre>
          </div>
          <div>
            <div style={{ fontWeight: 600, marginBottom: 6 }}>Stage 轮次记录</div>
            <pre style={{ fontSize: 12, color: '#ccc', background: '#12121e', borderRadius: 6, padding: 10, maxHeight: 180, overflow: 'auto', margin: 0 }}>{logStage || '暂无'}</pre>
          </div>
        </div>
      </Dialog>

      {/* 个股评分排名 */}
      <Card style={{ marginTop: 14 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
          <span>📊 个股评分排名</span>
          <span className="muted">N形≥60 / 龙头≥60 / 双凸≥60 / 回头≥60 / 动量≥50</span>
        </div>
        {evals.length ? (
          <Table
            data={sortedEvals}
            columns={evalColumns}
            rowKey="code"
            size="small"
            pagination={{ pageSize: 20, showJumper: true }}
          />
        ) : (
          <div className="muted" style={{ padding: 24, textAlign: 'center' }}>等待评估结果...</div>
        )}
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, fontSize: 11, color: '#888', marginTop: 10 }}>
          <span style={{ color: '#e34d59' }}>≥80 强势</span>
          <span style={{ color: '#FAAD14' }}>≥门槛 达标</span>
          <span style={{ color: '#555' }}>&lt;门槛 偏低</span>
          <span>|</span>
          <span>N形≥60操作, 龙头≥60买入/≥50观察, 双凸≥60买入/50-60观察, 回头≥60入场, 动量≥50关注</span>
          <span>|</span>
          <span>点击表头排序</span>
        </div>
      </Card>

      {/* 宏观日历 */}
      <Card style={{ marginTop: 14 }}>
        <div style={{ fontWeight: 600, marginBottom: 12 }}>📅 宏观日历</div>
        {calendarData.length ? (
          <Table data={calendarData} columns={calendarColumns} rowKey="id" size="small" pagination={false} maxHeight={200} />
        ) : (
          <div className="muted" style={{ padding: 16, textAlign: 'center' }}>暂无日历事件</div>
        )}
      </Card>

      {/* IPO 日历 */}
      <Card style={{ marginTop: 14 }}>
        <div style={{ fontWeight: 600, marginBottom: 12 }}>📋 IPO日历</div>
        {ipoData.length ? (
          <Table data={ipoData} columns={ipoColumns} rowKey="id" size="small" pagination={false} maxHeight={200} />
        ) : (
          <div className="muted" style={{ padding: 16, textAlign: 'center' }}>暂无IPO日历</div>
        )}
      </Card>

      {/* 热点资讯 */}
      <Card style={{ marginTop: 14 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
          <span>📰 热点资讯</span>
          <Button size="small" variant="outline" theme="primary" disabled={reanalyzing} onClick={onReanalyze}>
            {reanalyzing ? '补推中…' : '🔁 手动补推'}
          </Button>
        </div>
        {newsData.length ? (
          <Table data={newsData} columns={newsColumns} rowKey="id" size="small" pagination={false} maxHeight={400} />
        ) : (
          <div className="muted" style={{ padding: 16, textAlign: 'center' }}>暂无资讯</div>
        )}
      </Card>
    </div>
  )
}

// web/src/pages/Hotspot.vue
<!--
  热点页面 Hotspot.vue
  展示热点板块（含异动原因弹窗）、全市场个股评分排名、宏观日历、IPO日历、热点资讯
-->
<template>
  <div class="hotspot-page">
    <!-- 热点板块卡片网格 -->
    <div class="card">
      <div class="card-header">🔥 热点板块</div>
      <div class="sector-grid" v-if="sectors.length">
        <div v-for="s in sectors" :key="s.code" class="sector-card" @click="showReason(s)">
          <div class="sec-name">{{ s.name }}</div>
          <div v-if="s.reason" class="sec-reason">{{ shortReason(s.reason) }}</div>
          <div class="sec-score">{{ s.score?.toFixed(0) }}分</div>
          <div :class="['sec-pct', (s.change_pct || 0) >= 0 ? 'up' : 'down']">
            {{ (s.change_pct || 0) > 0 ? '+' : '' }}{{ (s.change_pct || 0).toFixed(2) }}%
          </div>
          <div class="sec-meta">
            <span v-if="(s.d1 || 0) > 0" class="d1-badge">D1 {{ s.d1.toFixed(0) }}</span>
            <span>涨停 {{ s.limitup_cnt || 0 }}</span>
            <span>流入 {{ s.net_inflow ? (s.net_inflow / 1e8).toFixed(1) + '亿' : '—' }}</span>
          </div>
        </div>
      </div>
      <div class="empty" v-else>暂无热点板块数据</div>
    </div>

    <!-- 热点板块异动原因弹窗 -->
    <div class="modal-overlay" v-if="reasonTarget" @click="reasonTarget = null"></div>
    <div class="modal" v-if="reasonTarget">
      <div class="modal-header">{{ reasonTarget.name }}</div>
      <div class="modal-body">
        <div class="modal-section">
          <div class="modal-subtitle">板块异动原因</div>
          <div class="modal-reason">{{ reasonTarget.reason_detail || reasonTarget.reason || '暂无' }}</div>
        </div>
        <div v-if="reasonTarget.news_titles && reasonTarget.news_titles.length" class="modal-section">
          <div class="modal-subtitle">触发新闻（{{ reasonTarget.news_titles.length }}条）</div>
          <div v-for="(t, i) in reasonTarget.news_titles" :key="i" class="modal-news-item">
            <span class="modal-news-idx">{{ i + 1 }}.</span>
            <span class="modal-news-title">{{ t }}</span>
          </div>
        </div>
      </div>
      <button class="modal-close" @click="reasonTarget = null">知道了</button>
    </div>

    <!-- 个股全维度评分排名（含排序功能） -->
    <div class="card" style="margin-top: 14px;">
      <div class="card-header">
        <span>📊 个股评分排名</span>
        <span class="card-sub">N形≥60 / 龙头≥70 / 双凸≥70 / 回头≥60 / 动量≥50</span>
      </div>
      <div class="eval-table" v-if="evals.length">
        <div class="ev-header">
          <span class="ev-code sortable" @click="setSort('code')">代码{{ sortArrow('code') }}</span>
          <span class="ev-name sortable" @click="setSort('name')">名称{{ sortArrow('name') }}</span>
          <span class="ev-price sortable" @click="setSort('price')">现价{{ sortArrow('price') }}</span>
          <span class="ev-chg sortable" @click="setSort('change_pct')">涨跌{{ sortArrow('change_pct') }}</span>
          <span class="ev-n sortable" @click="setSort('n_score')" title="N形≥60可操作">N≥60{{ sortArrow('n_score') }}</span>
          <span class="ev-dragon sortable" @click="setSort('dragon_score')" title="龙头≥70买入,≥50观察">龙≥70{{ sortArrow('dragon_score') }}</span>
          <span class="ev-db sortable" @click="setSort('db_score')" title="双凸≥70买入,50-70观察">凸≥70{{ sortArrow('db_score') }}</span>
          <span class="ev-dr sortable" @click="setSort('dr_score')" title="龙回头≥60首次入场">回≥60{{ sortArrow('dr_score') }}</span>
          <span class="ev-m sortable" @click="setSort('m_score')" title="动量≥50值得看">量≥50{{ sortArrow('m_score') }}</span>
        </div>
        <div class="ev-body">
          <div v-for="e in sortedEvals" :key="e.code" :class="rowClass(e)">
            <span class="ev-code">{{ e.code }}</span>
            <span class="ev-name">{{ e.name || '-' }}</span>
            <span class="ev-price">¥{{ (e.price || 0).toFixed(2) }}</span>
            <span :class="['ev-chg', (e.change_pct || 0) >= 0 ? 'up' : 'down']">
              {{ (e.change_pct || 0) > 0 ? '+' : '' }}{{ (e.change_pct || 0).toFixed(2) }}%
            </span>
            <span :class="scoreClass(e.n_score, e.n_pass, 80)">{{ e.n_score > 0 ? e.n_score.toFixed(0) : '—' }}</span>
            <span :class="scoreClass(e.dragon_score, e.dragon_pass, 80)">{{ e.dragon_score > 0 ? e.dragon_score.toFixed(0) : '—' }}</span>
            <span :class="scoreClass(e.db_score, e.db_pass, 80)">{{ e.db_score > 0 ? e.db_score.toFixed(0) : '—' }}</span>
            <span :class="scoreClass(e.dr_score, e.dr_pass, 80)">{{ e.dr_score > 0 ? e.dr_score.toFixed(0) : '—' }}</span>
            <span :class="scoreClass(e.m_score, e.m_pass, 70)">{{ e.m_score > 0 ? e.m_score.toFixed(0) : '—' }}</span>
          </div>
        </div>
      </div>
      <div class="empty" v-else>
        <span class="loading-dot"></span> 等待评估结果...
      </div>
      <div class="legend">
        <span class="lg-strong">≥80 强势</span>
        <span class="lg-pass">≥门槛 达标</span>
        <span class="lg-low">&lt;门槛 偏低</span>
        <span class="lg-sep">|</span>
        <span class="lg-item">N形≥60操作, 龙头≥70买入/≥50观察, 双凸≥70买入/50-70观察, 回头≥60入场, 动量≥50关注</span>
      <span class="lg-sep">|</span>
      <span class="lg-item">点击表头排序</span>
      </div>
    </div>

    <!-- 宏观日历 -->
    <div class="card" style="margin-top: 14px;">
      <div class="card-header">📅 宏观日历</div>
      <div class="hs-cal-scroll">
        <div v-for="(c, i) in calendarEvents" :key="'c'+i" class="hs-cal-item">
          <span class="hs-cal-date">{{ c.datetime ? c.datetime.slice(5, 10) : '' }}</span>
          <span class="hs-cal-title">{{ c.title }}</span>
        </div>
        <div v-if="!calendarEvents.length" class="hs-cal-empty">暂无日历事件</div>
      </div>
    </div>

    <!-- IPO日历 -->
    <div class="card" style="margin-top: 14px;">
      <div class="card-header">📋 IPO日历</div>
      <div class="hs-cal-scroll">
        <div v-for="(c, i) in ipoCalendar" :key="'ipo'+i" class="hs-cal-item">
          <span class="hs-cal-date">{{ c.listing_date ? c.listing_date.slice(5, 10) : (c.ipo_date ? c.ipo_date.slice(5, 10) : '') }}</span>
          <span class="hs-cal-title">{{ c.name }}（{{ c.code }}）</span>
          <span v-if="c.issue_price" class="cal-price">¥{{ c.issue_price.toFixed(2) }}</span>
              <span :class="['cal-status', c.list_status === 'L' ? 'cal-status-l' : 'cal-status-u']">{{ ipoCountdown(c) }}</span>
        </div>
        <div v-if="!ipoCalendar.length" class="hs-cal-empty">暂无IPO日历</div>
      </div>
    </div>

    <!-- 热点资讯列表 -->
    <div class="card" style="margin-top: 14px;">
      <div class="card-header">📰 热点资讯</div>
      <div v-if="newsItems.length" class="hs-news-scroll">
        <div v-for="(n, i) in newsItems" :key="i" class="hs-news-item">
          <div class="hs-news-head">
            <span class="hs-news-time">{{ n.datetime ? n.datetime.slice(5, 16) : '' }}</span>
            <span class="hs-news-title">{{ n.title }}</span>
          </div>
          <div class="hs-news-tags">
            <span v-if="n.sentiment" :class="['tag', 'tag-sent-' + n.sentiment]">{{ n.sentiment }}</span>
            <span v-if="n.direction" :class="['tag', n.direction === '利好' ? 'tag-up' : n.direction === '利空' ? 'tag-down' : 'tag-neutral']">{{ n.direction }}</span>
            <span v-if="n.impact_level" :class="['tag', 'tag-impact-' + n.impact_level]">{{ n.impact_level }}影响</span>
            <span v-if="n.sectors?.length" v-for="sec in n.sectors" :key="sec" class="sector-tag">{{ sec }}</span>
            <span v-if="n.stocks?.length" v-for="stk in n.stocks" :key="stk" class="stock-tag">{{ stk }}</span>
            <span v-if="!n.sentiment && !n.direction && !n.sectors?.length" class="tag-placeholder"></span>
          </div>
        </div>
      </div>
      <div class="empty" v-else>暂无资讯</div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import * as api from '../api/index.js'

// ── 工具函数 ──

/** 截取板块异动原因的前半段（第一个逗号前或前18字） */
function shortReason(r) {
  if (!r) return ''
  const idx = r.indexOf('，')
  return idx > 0 ? r.slice(0, idx) : r.slice(0, 18)
}

/** 根据评分阈值返回 CSS 类名 */
function scoreClass(score, pass, strongMin) {
  if (!score || score <= 0) return 'ev-score'
  if (score >= strongMin) return 'ev-score strong'
  if (pass) return 'ev-score pass'
  return 'ev-score'
}

/** 根据多维度评分判断行样式 */
function rowClass(e) {
  const strong = (e.n_score || 0) >= 80 || (e.dragon_score || 0) >= 80 || (e.db_score || 0) >= 80 || (e.dr_score || 0) >= 80 || (e.m_score || 0) >= 70
  if (strong) return 'ev-row strong'
  const watch = (e.n_score || 0) >= 60 || (e.dragon_score || 0) >= 70 || (e.db_score || 0) >= 70 || (e.dr_score || 0) >= 60 || (e.m_score || 0) >= 50
  if (watch) return 'ev-row watch'
  return 'ev-row'
}

// ── 排序状态 ──
const sortKey = ref('')
const sortDir = ref(-1)

function setSort(key) {
  if (sortKey.value === key) {
    sortDir.value *= -1
  } else {
    sortKey.value = key
    sortDir.value = -1
  }
}

function sortArrow(key) {
  if (sortKey.value !== key) return ''
  return sortDir.value === -1 ? ' ▼' : ' ▲'
}

function val(e, key) {
  const v = e[key]
  if (typeof v === 'string') return v || ''
  return v || 0
}

// ── 响应式数据 ──
const sectors = ref([])           // 热点板块
const evals = ref([])             // 全市场个股评分
const news = ref([])              // 资讯 + 日历事件
const ipoCalendar = ref([])       // IPO 日历
const reasonTarget = ref(null)    // 当前查看异动原因的板块

function showReason(s) { reasonTarget.value = s }

let timer = null
let unsubSSE = null
let loading = false              // 防并发请求标志

// ── 计算属性 ──
/** 过滤出非日历的普通资讯 */
const newsItems = computed(() => news.value.filter(n => n.source !== '宏观日历'))
/** 过滤出宏观日历事件 */
const calendarEvents = computed(() => news.value.filter(n => n.source === '宏观日历'))

/** IPO 倒计时文本 */
function ipoCountdown(c) {
  const ds = c.listing_date || c.ipo_date
  if (!ds) return c.list_status === 'L' ? '已上市' : '即将上市'
  const t = new Date(+ds.slice(0,4), +ds.slice(4,6)-1, +ds.slice(6,8))
  const diff = Math.ceil((t - Date.now()) / 86400000)
  if (diff > 0) return `${diff}天后`
  if (diff === 0) return '📌今天'
  return `${-diff}天前`
}

/** 全市场最高评分（用于缩放显示） */
const maxScore = computed(() => {
  let m = 0
  for (const e of evals.value) {
    const t = Math.max(e.n_score || 0, e.dragon_score || 0, e.db_score || 0, e.dr_score || 0, e.m_score || 0)
    if (t > m) m = t
  }
  return m || 100
})

/** 按排序列和方向排序后的评分列表 */
const sortedEvals = computed(() => {
  if (!evals.value || !evals.value.length) return []
  const arr = [...evals.value]
  const sk = sortKey.value
  if (!sk) {
    return arr.sort((a, b) => {
      const sa = Math.max(a.n_score || 0, a.dragon_score || 0, a.db_score || 0, a.dr_score || 0, a.m_score || 0)
      const sb = Math.max(b.n_score || 0, b.dragon_score || 0, b.db_score || 0, b.dr_score || 0, b.m_score || 0)
      return sb - sa
    })
  }
  const dir = sortDir.value
  return arr.sort((a, b) => {
    const va = val(a, sk)
    const vb = val(b, sk)
    if (typeof va === 'string') return va.localeCompare(vb) * dir
    return (va - vb) * dir
  })
})

// ── 数据加载 ──

/** 加载板块热点、评分、资讯、IPO 数据（带防并发） */
async function load() {
  if (loading) return
  loading = true
  try {
    const st = await api.fetchStatus()
    api.setLastSession(st.session)
    if (api.isTradingSession(st.session) || !evals.value.length) {
      try {
        const e = await api.fetchEvaluations()
        if (e) evals.value = e
      } catch (_) {}
    }
  } catch (_) {}
  try {
    const s = await api.fetchSectorHot()
    if (s) sectors.value = s
  } catch (_) {}
  try {
    const n = await api.fetchNews(true)
    if (n) news.value = n
  } catch (_) {}
  try {
    const ipo = await api.fetchIPOCalendar()
    if (ipo) ipoCalendar.value = ipo
  } catch (_) {}
  loading = false
}

/** SSE 触发刷新 */
function handleSSE() { load() }

onMounted(() => {
  load()
  timer = setInterval(load, 3000)
  api.connectSSE()
  unsubSSE = api.onSSE(handleSSE)
})
onUnmounted(() => {
  if (timer) clearInterval(timer)
  if (unsubSSE) { unsubSSE(); unsubSSE = null }
})
</script>

<style scoped>
.hotspot-page { max-width: 1200px; }
.card { background: #1a1a2e; border-radius: 8px; padding: 14px; }
.card-header { font-size: 14px; font-weight: 600; color: #ccc; margin-bottom: 10px; display: flex; align-items: center; justify-content: space-between; }
.card-sub { font-size: 11px; color: #666; font-weight: 400; }

.sector-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 10px; }
.sector-card { background: #0f0f23; border-radius: 6px; padding: 12px; cursor: pointer; }
.sector-card:active { opacity: 0.8; }
.sec-name { font-size: 14px; font-weight: 600; color: #e0e0e0; }
.sec-reason {
  font-size: 11px; color: #4fc3f7; margin-top: 2px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  background: rgba(79,195,247,0.08); border-radius: 3px; padding: 1px 6px; display: inline-block; max-width: 100%;
}

.modal-overlay {
  position: fixed; inset: 0; background: rgba(0,0,0,0.6);
  display: flex; align-items: center; justify-content: center; z-index: 100;
}
.modal {
  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 101;
  background: #1a1a2e; border-radius: 10px; padding: 20px; width: 85%; max-width: 360px;
  text-align: center;
}
.modal-header { font-size: 14px; font-weight: 600; color: #e0e0e0; margin-bottom: 10px; }
.modal-body { font-size: 12px; color: #ccc; line-height: 1.6; margin-bottom: 16px; word-break: break-word; text-align: left; max-height: 60vh; overflow-y: auto; }
.modal-section { margin-bottom: 12px; }
.modal-section:last-child { margin-bottom: 0; }
.modal-subtitle { font-size: 11px; color: #888; font-weight: 600; margin-bottom: 4px; border-bottom: 1px solid #2a2a3e; padding-bottom: 3px; }
.modal-reason { font-size: 12px; color: #e0e0e0; line-height: 1.7; white-space: pre-line; }
.modal-news-item { display: flex; gap: 4px; padding: 2px 0; font-size: 12px; line-height: 1.5; }
.modal-news-idx { color: #666; flex-shrink: 0; min-width: 18px; }
.modal-news-title { color: #ccc; }
.modal-close {
  padding: 8px 28px; border-radius: 8px; border: none;
  background: #FF4D4F; color: #fff; font-size: 13px; cursor: pointer;
}
.modal-close:active { opacity: 0.8; }
.sec-score { font-size: 11px; color: #FAAD14; margin-top: 4px; }
.sec-pct { font-size: 20px; font-weight: 700; margin-top: 4px; }
.sec-pct.up { color: #FF4D4F; }
.sec-pct.down { color: #4caf50; }
.sec-meta { display: flex; gap: 12px; font-size: 11px; color: #666; margin-top: 6px; }
.d1-badge { color: #b388ff; background: rgba(179,136,255,0.15); padding: 0 5px; border-radius: 3px; font-weight: 600; }

.eval-table { font-size: 12px; }
.ev-header, .ev-row { display: flex; align-items: center; padding: 4px 0; gap: 4px; }
.ev-header { color: #555; border-bottom: 1px solid #2a2a3e; font-weight: 600; }
.ev-row { border-bottom: 1px solid #1a1a26; }
.ev-row.watch { background: rgba(250,173,20,0.08); }
.ev-row.strong { background: rgba(255,77,79,0.10); }
.ev-row:last-child { border-bottom: none; }
.ev-code { width: 64px; font-family: monospace; color: #4fc3f7; }
.ev-name { width: 72px; color: #ccc; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.ev-price { width: 70px; text-align: right; color: #e0e0e0; }
.ev-chg { width: 62px; text-align: right; font-weight: 600; }
.ev-chg.up { color: #FF4D4F; }
.ev-chg.down { color: #4caf50; }
.ev-score, .ev-n, .ev-dragon, .ev-db, .ev-dr, .ev-m { width: 40px; text-align: center; color: #555; font-weight: 600; }
.ev-score.pass { color: #FAAD14; }
.ev-score.strong { color: #FF4D4F; }
.sortable { cursor: pointer; user-select: none; }
.sortable:hover { color: #ccc; }
.ev-body { max-height: 400px; overflow-y: auto; }
.ev-body::-webkit-scrollbar { width: 4px; }
.ev-body::-webkit-scrollbar-thumb { background: #333; border-radius: 2px; }

.hs-cal-scroll { max-height: 80px; overflow-y: auto; }
.hs-cal-item { display: flex; align-items: center; gap: 8px; padding: 3px 0; font-size: 12px; }
.hs-cal-date { color: #888; width: 76px; flex-shrink: 0; font-size: 11px; }
.hs-cal-title { flex: 1; color: #e0e0e0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 12px; }
.hs-cal-empty { font-size: 12px; color: #555; padding: 6px 0; }
.cal-price { width: 60px; text-align: right; color: #4fc3f7; font-size: 11px; flex-shrink: 0; }
.cal-status { width: 56px; text-align: right; font-size: 10px; padding: 1px 6px; border-radius: 3px; flex-shrink: 0; }
.cal-status-l { color: #888; background: rgba(136,136,136,0.15); }
.cal-status-u { color: #FAAD14; background: rgba(250,173,20,0.15); }
.hs-news-scroll { max-height: 400px; overflow-y: auto; }
.hs-news-item { padding: 6px 0; border-bottom: 1px solid #1a1a26; }
.hs-news-item:last-child { border-bottom: none; }
.hs-news-head { display: flex; gap: 8px; align-items: flex-start; }
.hs-news-time { color: #888; width: 76px; flex-shrink: 0; font-size: 11px; line-height: 16px; }
.hs-news-title { flex: 1; color: #ccc; font-size: 12px; line-height: 16px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.hs-news-tags { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 3px; margin-left: 84px; min-height: 16px; }
.tag-placeholder { display: inline-block; width: 1px; height: 16px; }
.tag { font-size: 10px; padding: 1px 6px; border-radius: 3px; white-space: nowrap; }
.tag-sent-正面 { background: #1a3a1a; color: #4caf50; }
.tag-sent-负面 { background: #3a1a1a; color: #ff4d4f; }
.tag-sent-中性 { background: #2a2a2a; color: #999; }
.tag-up { background: #1a3a1a; color: #4caf50; }
.tag-down { background: #3a1a1a; color: #ff4d4f; }
.tag-neutral { background: #2a2a2a; color: #999; }
.tag-impact-高 { background: #3a2a1a; color: #faad14; }
.tag-impact-中 { background: #2a2a3a; color: #4fc3f7; }
.tag-impact-低 { background: #2a2a2a; color: #666; }
.tag-type { background: #1a2a3a; color: #4fc3f7; }
.tag-strategy { background: #2a1a3a; color: #b388ff; }
.tag-urgent { background: #3a1a1a; color: #ff4d4f; font-weight: 600; }
.tag-watch { background: #3a2a1a; color: #faad14; }
.tag-obs { background: #2a2a2a; color: #666; }
.sector-label { font-size: 10px; color: #555; padding: 1px 0; }
.sector-tag { font-size: 10px; padding: 1px 6px; border-radius: 3px; background: rgba(179,136,255,0.15); color: #b388ff; white-space: nowrap; }
.stock-tag { font-size: 10px; padding: 1px 6px; border-radius: 3px; background: rgba(255,152,0,0.15); color: #FF9800; font-family: monospace; }
.empty { text-align: center; padding: 30px; color: #555; font-size: 12px; }
.loading-dot { display: inline-block; width: 6px; height: 6px; background: #4fc3f7; border-radius: 50%; margin-right: 6px; animation: pulse 1.5s infinite; }
@keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.3; } 100% { opacity: 1; } }
.legend {
  margin-top: 8px; padding: 6px 12px; font-size: 11px; color: #666;
  background: #1a1a2e; border-radius: 6px; display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
}
.lg-strong { color: #FF4D4F; }
.lg-pass { color: #FAAD14; }
.lg-low { color: #555; }
.lg-sep { color: #333; }
.lg-item { color: #666; }
</style>
