// web/src/pages/LLMDebug.jsx
// ── LLM 分析诊断页面 LLMDebug.jsx ──
// 展示最新一轮 Stage 流水线结果（Stage1 初筛 / Stage2 事件分析），
// 并内嵌 Dialog + Tabs 弹窗用于按批次查看 LLM 分析与信号批次日志。
// 使用 TDesign React 组件（Card / Table / Tag / Button / Dialog / Tabs / Input / Select）。
import React, { useState, useEffect, useMemo, useCallback } from 'react'
import { Card, Table, Tag, Button, Dialog, Tabs, Input, Select } from 'tdesign-react'
import * as api from '../api/index.js'
import { showToast } from '../ui.jsx'

// 根据新闻/信号方向（利好/利空/中性）返回对应的 TDesign Tag 主题色
function dirTheme(d) {
  if (d === '利好') return 'success'
  if (d === '利空') return 'danger'
  return 'warning'
}

// 将标签数组渲染为一组 TDesign Tag；kind 为 'stock' 时使用 warning 主题区分个股标签
function TagList({ items, kind }) {
  if (!items || !items.length) return <span className="muted">—</span>
  return (
    <span style={{ display: 'inline-flex', gap: 4, flexWrap: 'wrap' }}>
      {items.map((s, i) => (
        <Tag key={i} size="small" theme={kind === 'stock' ? 'warning' : 'primary'} variant="light">{s}</Tag>
      ))}
    </span>
  )
}

// 工具栏容器样式（搜索框 + 批次下拉 + 刷新按钮）
const toolbarStyle = { display: 'flex', gap: 8, alignItems: 'center', marginBottom: 12, flexWrap: 'wrap' }
// 顶部统计条样式：横向排列原始条数 / 筛选后 / 分析时间等指标
const summaryBarStyle = { display: 'flex', gap: 24, flexWrap: 'wrap', fontSize: 13, padding: '4px 0' }
// 单个统计项：标签在上、数值在下
const summaryItemStyle = { display: 'flex', flexDirection: 'column', gap: 2 }
// 空数据占位样式
const emptyStyle = { textAlign: 'center', color: '#888', padding: 24 }

/**
 * 日志弹窗子组件（LLM 分析 / 信号批次）
 * 按轮次展示 Stage 流水线记录，支持跨批次搜索与战法筛选。
 * @param {{visible:boolean, onClose:()=>void}} props
 * @returns {JSX.Element|null}
 */
function LogModal({ visible, onClose }) {
  const [activeTab, setActiveTab] = useState('llm')
  const [loading, setLoading] = useState(false)

  const [llmRecords, setLlmRecords] = useState([])
  const [llmIdx, setLlmIdx] = useState(0)
  const [llmData, setLlmData] = useState(null)
  const [llmNoData, setLlmNoData] = useState(false)
  const [llmQuery, setLlmQuery] = useState('')
  const [selectedSet, setSelectedSet] = useState(new Set())

  const [sigRecords, setSigRecords] = useState([])
  const [sigIdx, setSigIdx] = useState(0)
  const [sigData, setSigData] = useState(null)
  const [sigNoData, setSigNoData] = useState(false)
  const [sigQuery, setSigQuery] = useState('')
  const [activeSigStrategy, setActiveSigStrategy] = useState('all')

  // 格式化时间为 HH:mm:ss
  function fmtTime(t) {
    if (!t) return '-'
    const d = new Date(t)
    return d.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
  }

  // 判断 Stage1 初筛中第 i 条是否被 LLM 选中
  const isSelected = (i) => selectedSet.has(i)

  // 将当前选中的 LLM 轮次数据应用到展示态
  function applyLLM() {
    const r = llmRecords[llmIdx]
    setLlmData(r || null)
    setLlmNoData(!r)
    setSelectedSet(new Set(r ? r.selected_idx || [] : []))
  }
  // 将当前选中的信号批次数据应用到展示态
  function applySignal() {
    const r = sigRecords[sigIdx]
    setSigData(r || null)
    setSigNoData(!r)
  }

  // 判断文本是否包含查询词（不区分大小写）
  function hasText(text, q) {
    if (!text || !q) return false
    return String(text).toUpperCase().includes(q)
  }
  // 判断事件对象是否命中搜索条件（标题/理由/板块/个股）
  function eventHit(ev, q) {
    if (!ev) return false
    if (hasText(ev.title, q)) return true
    if (hasText(ev.reason, q)) return true
    if (ev.sectors && ev.sectors.some((s) => hasText(s, q))) return true
    if (ev.related_stocks && ev.related_stocks.some((s) => hasText(s, q))) return true
    if (ev.cleaned_stocks && ev.cleaned_stocks.some((s) => hasText(s, q))) return true
    return false
  }
  // 判断信号对象是否命中搜索条件（代码/名称/板块/战法/理由）
  function sigHit(sg, q) {
    if (!sg) return false
    if (hasText(sg.code, q)) return true
    if (hasText(sg.name, q)) return true
    if (hasText(sg.sector, q)) return true
    if (hasText(sg.strategy, q)) return true
    if (hasText(sg.reason, q)) return true
    return false
  }

  const sigStrategyOptions = useMemo(() => {
    const set = new Set()
    for (const r of sigRecords) {
      for (const sg of (r.signals || [])) {
        if (sg.strategy) set.add(sg.strategy)
      }
    }
    return [...set].map((s) => ({ label: s, value: s }))
  }, [sigRecords])

  const sigFiltered = useMemo(() => {
    const sigs = sigData?.signals || []
    if (activeSigStrategy === 'all') return sigs
    return sigs.filter((sg) => sg.strategy === activeSigStrategy)
  }, [sigData, activeSigStrategy])

  const llmSearching = (llmQuery || '').trim() !== ''
  const sigSearching = (sigQuery || '').trim() !== ''
  const llmSearchGroups = useMemo(() => {
    const q = (llmQuery || '').trim().toUpperCase()
    if (!q) return []
    const groups = []
    for (const r of llmRecords) {
      const items = (r.stage2_events || []).filter((ev) => eventHit(ev, q))
      if (items.length) groups.push({ time: r.process_time, items })
    }
    return groups
  }, [llmRecords, llmQuery])
  const llmTotalHits = llmSearchGroups.reduce((n, g) => n + g.items.length, 0)
  const sigSearchGroups = useMemo(() => {
    const q = (sigQuery || '').trim().toUpperCase()
    if (!q) return []
    const groups = []
    for (const r of sigRecords) {
      const items = (r.signals || []).filter((sg) => sigHit(sg, q) && (activeSigStrategy === 'all' || sg.strategy === activeSigStrategy))
      if (items.length) groups.push({ time: r.process_time, items })
    }
    return groups
  }, [sigRecords, sigQuery, activeSigStrategy])
  const sigTotalHits = sigSearchGroups.reduce((n, g) => n + g.items.length, 0)

  // 加载 Stage 记录与信号批次日志，并更新默认选中项
  const load = useCallback(async () => {
    if (loading) return
    setLoading(true)
    const [srRes, slRes] = await Promise.allSettled([api.fetchStageRecords(), api.fetchSignalLogs()])
    if (srRes.status === 'fulfilled' && Array.isArray(srRes.value) && srRes.value.length) {
      setLlmRecords(srRes.value)
      setLlmIdx(0)
      applyLLM()
    } else {
      setLlmRecords([])
      setLlmData(null)
      setLlmNoData(true)
    }
    if (slRes.status === 'fulfilled' && Array.isArray(slRes.value) && slRes.value.length) {
      setSigRecords(slRes.value)
      setSigIdx(0)
      applySignal()
    } else {
      setSigRecords([])
      setSigData(null)
      setSigNoData(true)
    }
    setLoading(false)
  }, [loading])

  // 切换日志弹窗标签：无数据时自动加载
  function switchTab(t) {
    setActiveTab(t)
    if ((t === 'llm' && llmData) || (t === 'signal' && sigData)) return
    if (!llmRecords.length && !sigRecords.length) load()
  }

  // 弹窗显示时自动加载日志
  useEffect(() => {
    if (visible) load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [visible])

  const llmBatchOptions = llmRecords.map((r, i) => ({
    label: `轮次 ${llmRecords.length - i} · ${fmtTime(r.process_time)}（${r.raw_count} 条 / 选 ${r.selected_count}）`,
    value: i,
  }))
  const sigBatchOptions = sigRecords.map((r, i) => ({
    label: `批次 ${sigRecords.length - i} · ${fmtTime(r.process_time)}（${r.signals.length} 信号 / ${r.raw_count} 条）`,
    value: i,
  }))

  // Stage1 初筛表格列定义：序号 / 标题 / 是否通过筛选
  const stage1Columns = [
    { colKey: 'idx', title: '#', width: 60 },
    { colKey: 'title', title: '标题', ellipsis: true },
    {
      colKey: 'sel', title: '筛选', width: 90,
      cell: ({ row }) => (
        <Tag theme={row.sel ? 'success' : 'default'} variant="light" size="small">
          {row.sel ? '通过' : '过滤'}
        </Tag>
      ),
    },
  ]
  // Stage2 事件分析表格列定义：标题 / 方向 / 评分 / 板块 / 个股 / 上下游 / 影响 / 类型 / 理由
  const stage2Columns = [
    { colKey: 'title', title: '标题', ellipsis: true, minWidth: 160 },
    {
      colKey: 'direction', title: '方向', width: 80,
      cell: ({ row }) => <Tag theme={dirTheme(row.direction)} size="small">{row.direction || '中性'}</Tag>,
    },
    { colKey: 'score', title: '评分', width: 90, cell: ({ row }) => Number(row.score || 0).toFixed(2) },
    { colKey: 'sectors', title: '板块', minWidth: 120, cell: ({ row }) => <TagList items={row.sectors} /> },
    { colKey: 'stocks', title: '个股', minWidth: 120, cell: ({ row }) => <TagList items={row.related_stocks} kind="stock" /> },
    { colKey: 'upstream', title: '上游', minWidth: 100, cell: ({ row }) => <TagList items={row.upstream_sectors} /> },
    { colKey: 'downstream', title: '下游', minWidth: 100, cell: ({ row }) => <TagList items={row.downstream_sectors} /> },
    {
      colKey: 'impact', title: '影响', width: 80,
      cell: ({ row }) => row.impact_level
        ? <Tag size="small" theme={row.impact_level === '高' ? 'danger' : row.impact_level === '中' ? 'warning' : 'default'} variant="light">{row.impact_level}</Tag>
        : <span className="muted">—</span>,
    },
    {
      colKey: 'type', title: '类型', width: 110,
      cell: ({ row }) => row.event_type ? <Tag size="small" variant="light">{row.event_type}</Tag> : <span className="muted">—</span>,
    },
    { colKey: 'reason', title: '理由', ellipsis: true, minWidth: 160 },
  ]

  // 信号批次表格列定义：代码 / 名称 / 战法 / 方向 / 动作 / 置信 / 现价 / 板块 / 理由
  const signalColumns = [
    { colKey: 'code', title: '代码', width: 90 },
    { colKey: 'name', title: '名称', width: 100 },
    { colKey: 'strategy', title: '战法', width: 130 },
    { colKey: 'direction', title: '方向', width: 80, cell: ({ row }) => <Tag theme={dirTheme(row.direction)} size="small">{row.direction || '中性'}</Tag> },
    { colKey: 'action', title: '动作', width: 80, cell: ({ row }) => <Tag size="small" variant="light">{row.action || '-'}</Tag> },
    { colKey: 'confidence', title: '置信', width: 90, cell: ({ row }) => Number(row.confidence || 0).toFixed(2) },
    { colKey: 'price', title: '现价', width: 90, cell: ({ row }) => row.price ? '¥' + Number(row.price).toFixed(2) : '-' },
    { colKey: 'sector', title: '板块', width: 120, ellipsis: true },
    { colKey: 'reason', title: '理由', ellipsis: true, minWidth: 160 },
  ]

  return (
    <Dialog visible={visible} onClose={onClose} header="📋 日志" width="900px" footer={false}>
      <div>
        <Tabs value={activeTab} onChange={(v) => switchTab(v)}>
          <Tabs.TabPanel value="llm" label="LLM 分析">
            <div className="toolbar" style={toolbarStyle}>
              <Input
                value={llmQuery}
                onChange={(v) => setLlmQuery(v)}
                placeholder="搜索：个股名称 / 代码 / 板块（跨批次）"
                style={{ flex: 1 }}
              />
              {!llmSearching && (
                <Select
                  value={llmIdx}
                  options={llmBatchOptions}
                  onChange={(v) => { setLlmIdx(Number(v)); applyLLM() }}
                  disabled={llmRecords.length < 2}
                  style={{ width: 320 }}
                />
              )}
              <Button theme="default" variant="outline" onClick={load} loading={loading}>刷新</Button>
            </div>

            {llmSearching ? (
              <div>
                {!llmSearchGroups.length ? (
                  <div style={emptyStyle}>未找到匹配项（可试：代码 / 名称 / 板块关键词）</div>
                ) : (
                  <>
                    <div className="muted" style={{ marginBottom: 8 }}>共 {llmTotalHits} 条事件命中，跨 {llmSearchGroups.length} 个轮次</div>
                    {llmSearchGroups.map((g, gi) => (
                      <div key={gi} style={{ marginBottom: 12 }}>
                        <div style={{ display: 'flex', gap: 12, marginBottom: 4, fontSize: 13 }}>
                          <span className="muted">轮次 {fmtTime(g.time)}</span>
                          <span className="muted">命中 {g.items.length} 条</span>
                        </div>
                        <Table
                          data={g.items.map((ev, i) => ({ ...ev, _k: gi + '_' + i }))}
                          columns={stage2Columns}
                          rowKey="_k"
                          size="small"
                          pagination={false}
                        />
                      </div>
                    ))}
                  </>
                )}
              </div>
            ) : (
              <>
                {llmNoData && <div style={emptyStyle}>暂无 LLM 分析记录，等待下一轮扫描</div>}
                {llmData && (
                  <>
                    <div style={summaryBarStyle}>
                      <div style={summaryItemStyle}>
                        <span className="muted">Stage1 模式</span>
                        <span style={{ color: llmData.stage1_mode === 'llm' ? '#0052d9' : '#faad14', fontWeight: 600 }}>
                          {llmData.stage1_mode === 'llm' ? 'LLM' : '关键词'}
                        </span>
                      </div>
                      <div style={summaryItemStyle}><span className="muted">原始条数</span><span style={{ color: '#1a1a1a' }}>{llmData.raw_count}</span></div>
                      <div style={summaryItemStyle}><span className="muted">筛选后</span><span style={{ color: '#1a1a1a' }}>{llmData.selected_count}</span></div>
                      <div style={summaryItemStyle}><span className="muted">分析时间</span><span style={{ color: '#1a1a1a' }}>{fmtTime(llmData.process_time)}</span></div>
                    </div>

                    <SectionLabel>Stage1 · 新闻初筛</SectionLabel>
                    <Table
                      data={(llmData.raw_titles || []).map((t, i) => ({ idx: i + 1, title: t, sel: isSelected(i) }))}
                      columns={stage1Columns}
                      rowKey="idx"
                      size="small"
                      pagination={false}
                    />

                    <SectionLabel>Stage2 · LLM 分析结果</SectionLabel>
                    {llmData.stage2_events && llmData.stage2_events.length > 0 ? (
                      <Table
                        data={llmData.stage2_events.map((ev, i) => ({ ...ev, _k: i }))}
                        columns={stage2Columns}
                        rowKey="_k"
                        size="small"
                        pagination={{ pageSize: 10, showJumper: true }}
                      />
                    ) : (
                      <div style={emptyStyle}>Stage2 无分析结果</div>
                    )}
                  </>
                )}
              </>
            )}
          </Tabs.TabPanel>

          <Tabs.TabPanel value="signal" label="信号批次">
            <div className="toolbar" style={toolbarStyle}>
              <Input
                value={sigQuery}
                onChange={(v) => setSigQuery(v)}
                placeholder="搜索：个股名称 / 代码 / 板块（跨批次）"
                style={{ flex: 1 }}
              />
              <Select
                value={activeSigStrategy}
                options={[{ label: '全部战法', value: 'all' }, ...sigStrategyOptions]}
                onChange={(v) => setActiveSigStrategy(v)}
                style={{ width: 160 }}
              />
              {!sigSearching && (
                <Select
                  value={sigIdx}
                  options={sigBatchOptions}
                  onChange={(v) => { setSigIdx(Number(v)); applySignal() }}
                  disabled={sigRecords.length < 2}
                  style={{ width: 320 }}
                />
              )}
              <Button theme="default" variant="outline" onClick={load} loading={loading}>刷新</Button>
            </div>

            {sigSearching ? (
              <div>
                {!sigSearchGroups.length ? (
                  <div style={emptyStyle}>未找到匹配项（可试：代码 / 名称 / 板块关键词）</div>
                ) : (
                  <>
                    <div className="muted" style={{ marginBottom: 8 }}>共 {sigTotalHits} 条信号命中，跨 {sigSearchGroups.length} 个批次</div>
                    {sigSearchGroups.map((g, gi) => (
                      <div key={gi} style={{ marginBottom: 12 }}>
                        <div style={{ display: 'flex', gap: 12, marginBottom: 4, fontSize: 13 }}>
                          <span className="muted">批次 {fmtTime(g.time)}</span>
                          <span className="muted">命中 {g.items.length} 条</span>
                        </div>
                        <Table
                          data={g.items.map((sg, i) => ({ ...sg, _k: gi + '_' + i }))}
                          columns={signalColumns}
                          rowKey="_k"
                          size="small"
                          pagination={false}
                        />
                      </div>
                    ))}
                  </>
                )}
              </div>
            ) : (
              <>
                {sigNoData && <div style={emptyStyle}>暂无信号批次记录，等待下一轮扫描</div>}
                {sigData && (
                  <>
                    <div style={summaryBarStyle}>
                      <div style={summaryItemStyle}><span className="muted">批次时间</span><span style={{ color: '#1a1a1a' }}>{fmtTime(sigData.process_time)}</span></div>
                      <div style={summaryItemStyle}><span className="muted">原始条数</span><span style={{ color: '#1a1a1a' }}>{sigData.raw_count}</span></div>
                      <div style={summaryItemStyle}><span className="muted">信号数</span><span style={{ color: '#1a1a1a' }}>{sigData.signals.length}</span></div>
                    </div>
                    {sigFiltered.length > 0 ? (
                      <Table
                        data={sigFiltered.map((sg, i) => ({ ...sg, _k: i }))}
                        columns={signalColumns}
                        rowKey="_k"
                        size="small"
                        pagination={{ pageSize: 10, showJumper: true }}
                      />
                    ) : (
                      <div style={emptyStyle}>{sigData.signals.length ? '当前战法无匹配信号' : '本轮无信号产出'}</div>
                    )}
                  </>
                )}
              </>
            )}
          </Tabs.TabPanel>
        </Tabs>
      </div>
    </Dialog>
  )
}

/**
 * LLM 分析诊断页面组件
 * 拉取最新 Stage 流水线记录并展示 Stage1 初筛、Stage2 事件分析详情。
 * @returns {JSX.Element}
 */
export default function LLMDebug() {
  const [loading, setLoading] = useState(false)
  const [records, setRecords] = useState([])
  const [data, setData] = useState(null)
  const [noAgent, setNoAgent] = useState(false)
  const [noData, setNoData] = useState(false)
  const [showLog, setShowLog] = useState(false)

  const [selectedSet, setSelectedSet] = useState(new Set())

  const isSelected = (i) => selectedSet.has(i)

  // 取最新一轮 Stage 记录更新页面展示态
  function applyLatest() {
    const r = records[0] || null
    setData(r)
    setNoAgent(false)
    setNoData(!r)
    setSelectedSet(new Set(r ? r.selected_idx || [] : []))
  }

  // 格式化时间为 HH:mm:ss
  function formatTime(t) {
    if (!t) return '-'
    const d = new Date(t)
    return d.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
  }

  // 拉取 Stage 记录并处理 Agent 未就绪、无数据、正常数据三种状态
  async function loadData() {
    setLoading(true)
    try {
      const res = await api.fetchStageRecords()
      if (res && res.status === 'no_engine') {
        setNoAgent(true)
        setNoData(false)
        setRecords([])
        setData(null)
      } else if (!Array.isArray(res) || res.length === 0) {
        setNoData(true)
        setNoAgent(false)
        setRecords([])
        setData(null)
      } else {
        setRecords(res)
        applyLatest()
      }
    } catch (e) {
      console.error('LLMDebug 加载失败', e)
    } finally {
      setLoading(false)
    }
  }

  // 页面挂载时加载最新 Stage 记录
  useEffect(() => { loadData() }, [])

  // Stage1 初筛表格列定义：序号 / 标题 / 是否通过筛选
  const stage1Columns = [
    { colKey: 'idx', title: '#', width: 60 },
    { colKey: 'title', title: '标题', ellipsis: true },
    {
      colKey: 'sel', title: '筛选', width: 90,
      cell: ({ row }) => (
        <Tag theme={row.sel ? 'success' : 'default'} variant="light" size="small">
          {row.sel ? '通过' : '过滤'}
        </Tag>
      ),
    },
  ]
  // Stage2 事件分析表格列定义：标题 / 方向 / 评分 / 板块 / 个股 / 上下游 / 影响 / 类型 / 理由
  const stage2Columns = [
    { colKey: 'title', title: '标题', ellipsis: true, minWidth: 160 },
    {
      colKey: 'direction', title: '方向', width: 80,
      cell: ({ row }) => <Tag theme={dirTheme(row.direction)} size="small">{row.direction || '中性'}</Tag>,
    },
    { colKey: 'score', title: '评分', width: 90, cell: ({ row }) => Number(row.score || 0).toFixed(2) },
    { colKey: 'sectors', title: '板块', minWidth: 120, cell: ({ row }) => <TagList items={row.sectors} /> },
    { colKey: 'stocks', title: '个股', minWidth: 120, cell: ({ row }) => <TagList items={row.related_stocks} kind="stock" /> },
    { colKey: 'upstream', title: '上游', minWidth: 100, cell: ({ row }) => <TagList items={row.upstream_sectors} /> },
    { colKey: 'downstream', title: '下游', minWidth: 100, cell: ({ row }) => <TagList items={row.downstream_sectors} /> },
    {
      colKey: 'impact', title: '影响', width: 80,
      cell: ({ row }) => row.impact_level
        ? <Tag size="small" theme={row.impact_level === '高' ? 'danger' : row.impact_level === '中' ? 'warning' : 'default'} variant="light">{row.impact_level}</Tag>
        : <span className="muted">—</span>,
    },
    {
      colKey: 'type', title: '类型', width: 110,
      cell: ({ row }) => row.event_type ? <Tag size="small" variant="light">{row.event_type}</Tag> : <span className="muted">—</span>,
    },
    { colKey: 'reason', title: '理由', ellipsis: true, minWidth: 160 },
  ]

  return (
    <div className="page">
      <div className="toolbar" style={{ justifyContent: 'space-between', marginBottom: 16 }}>
        <SectionLabel>LLM 分析诊断</SectionLabel>
        <div style={{ display: 'flex', gap: 8 }}>
          <Button theme="default" variant="outline" onClick={() => setShowLog(true)}>📋 日志</Button>
          <Button theme="primary" onClick={loadData} loading={loading}>刷新</Button>
        </div>
      </div>
      <LogModal visible={showLog} onClose={() => setShowLog(false)} />

      {noAgent && <div style={emptyStyle}>Agent 未就绪</div>}
      {!noAgent && noData && <div style={emptyStyle}>暂无数据，等待下一轮扫描</div>}
      {data && (
        <>
          <Card style={{ marginBottom: 16 }}>
            <div style={summaryBarStyle}>
              <div style={summaryItemStyle}>
                <span className="muted">Stage1 模式</span>
                <span style={{ color: data.stage1_mode === 'llm' ? '#0052d9' : '#faad14', fontWeight: 600 }}>
                  {data.stage1_mode === 'llm' ? 'LLM' : '关键词'}
                </span>
              </div>
              <div style={summaryItemStyle}><span className="muted">原始条数</span><span style={{ color: '#1a1a1a' }}>{data.raw_count}</span></div>
              <div style={summaryItemStyle}><span className="muted">筛选后</span><span style={{ color: '#1a1a1a' }}>{data.selected_count}</span></div>
              <div style={summaryItemStyle}><span className="muted">分析时间</span><span style={{ color: '#1a1a1a' }}>{formatTime(data.process_time)}</span></div>
            </div>
          </Card>

          <Card title="Stage1 · 新闻初筛" style={{ marginBottom: 16 }}>
            <Table
              data={(data.raw_titles || []).map((t, i) => ({ idx: i + 1, title: t, sel: isSelected(i) }))}
              columns={stage1Columns}
              rowKey="idx"
              size="small"
              pagination={false}
            />
          </Card>

          <Card title="Stage2 · LLM 分析结果">
            {data.stage2_events && data.stage2_events.length > 0 ? (
              <Table
                data={data.stage2_events.map((ev, i) => ({ ...ev, _k: i }))}
                columns={stage2Columns}
                rowKey="_k"
                size="small"
                pagination={{ pageSize: 10, showJumper: true }}
              />
            ) : (
              <div style={emptyStyle}>Stage2 无分析结果</div>
            )}
          </Card>
        </>
      )}
    </div>
  )
}

// 板块小标题
function SectionLabel({ children }) {
  return <div style={{ fontWeight: 600, margin: '8px 0 4px', fontSize: 13 }}>{children}</div>
}

// web/src/pages/LLMDebug.vue
<!--
  LLM 分析诊断页面 LLMDebug.vue
  展示 LLM 新闻分析管线两阶段结果：Stage1 关键词初筛 + Stage2 LLM 深度分析
-->
<template>
  <div class="llm-debug-page">
    <!-- 页头：标题 + 轮次选择 + 刷新按钮 -->
    <div class="page-header">
      <h2>LLM 分析诊断</h2>
      <div class="header-right">
        <select class="round-select" v-model="roundIdx" :disabled="records.length < 2" @change="applyRound">
          <option v-for="(r, i) in records" :key="r.process_time" :value="i">
            轮次 {{ records.length - i }} · {{ formatTime(r.process_time) }}（{{ r.raw_count }} 条 / 选 {{ r.selected_count }}）
          </option>
        </select>
        <button class="btn-refresh" @click="loadData" :disabled="loading">
          {{ loading ? '加载中...' : '刷新' }}
        </button>
      </div>
    </div>

    <!-- 状态判断 -->
    <div v-if="noAgent" class="empty">Agent 未就绪</div>
    <div v-else-if="noData" class="empty">暂无数据，等待下一轮扫描</div>
    <template v-else-if="data">
      <!-- 概要统计栏 -->
      <div class="summary-bar">
        <div class="summary-item">
          <span class="summary-label">Stage1 模式</span>
          <span :class="['summary-value', 'tag-' + data.stage1_mode]">{{ data.stage1_mode === 'llm' ? 'LLM' : '关键词' }}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">原始条数</span>
          <span class="summary-value">{{ data.raw_count }}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">筛选后</span>
          <span class="summary-value">{{ data.selected_count }}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">分析时间</span>
          <span class="summary-value">{{ formatTime(data.process_time) }}</span>
        </div>
      </div>

      <!-- Stage1：新闻初筛标题列表，标注通过/过滤 -->
      <h3 class="section-title">Stage1 · 新闻初筛</h3>
      <div class="stage1-list">
        <div v-for="(title, i) in data.raw_titles" :key="i"
          :class="['title-item', isSelected(i) ? 'selected' : 'discarded']">
          <span class="title-idx">{{ i + 1 }}</span>
          <span class="title-text">{{ title }}</span>
          <span :class="['title-badge', isSelected(i) ? 'badge-pass' : 'badge-skip']">
            {{ isSelected(i) ? '通过' : '过滤' }}
          </span>
        </div>
      </div>

      <!-- Stage2：LLM 深度分析事件卡片 -->
      <h3 class="section-title">Stage2 · LLM 分析结果</h3>
      <div class="stage2-events" v-if="data.stage2_events && data.stage2_events.length">
        <div v-for="(ev, i) in data.stage2_events" :key="i" class="event-card">
          <div class="event-header">
            <span class="event-title">{{ ev.title }}</span>
            <span :class="['tag', 'tag-' + ev.direction]">{{ ev.direction || '中性' }}</span>
            <span class="event-score">评分 {{ (ev.score || 0).toFixed(2) }}</span>
          </div>
          <div class="event-body">
            <div class="event-row" v-if="ev.sectors && ev.sectors.length">
              <span class="event-label">板块</span>
              <span class="event-tags">
                <span v-for="s in ev.sectors" :key="s" class="mini-tag sector">{{ s }}</span>
              </span>
            </div>
            <div class="event-row" v-if="ev.related_stocks && ev.related_stocks.length">
              <span class="event-label">个股</span>
              <span class="event-tags">
                <span v-for="s in ev.related_stocks" :key="s" class="mini-tag stock">{{ s }}</span>
              </span>
            </div>
            <div class="event-row" v-if="ev.upstream_sectors && ev.upstream_sectors.length">
              <span class="event-label">上游</span>
              <span class="event-tags">
                <span v-for="s in ev.upstream_sectors" :key="s" class="mini-tag sector">{{ s }}</span>
              </span>
            </div>
            <div class="event-row" v-if="ev.downstream_sectors && ev.downstream_sectors.length">
              <span class="event-label">下游</span>
              <span class="event-tags">
                <span v-for="s in ev.downstream_sectors" :key="s" class="mini-tag sector">{{ s }}</span>
              </span>
            </div>
            <div class="event-row" v-if="ev.impact_level">
              <span class="event-label">影响</span>
              <span :class="['mini-tag', 'impact-' + ev.impact_level]">{{ ev.impact_level }}</span>
            </div>
            <div class="event-row" v-if="ev.event_type">
              <span class="event-label">类型</span>
              <span class="mini-tag">{{ ev.event_type }}</span>
            </div>
            <div class="event-row" v-if="ev.reason">
              <span class="event-label">理由</span>
              <span class="event-reason">{{ ev.reason }}</span>
            </div>
          </div>
        </div>
      </div>
      <div v-else class="empty">Stage2 无分析结果</div>
    </template>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import * as api from '../api/index.js'

// ── 响应式状态 ──
const loading = ref(false)        // 是否正在加载
const records = ref([])           // 当日全量轮次记录（持久化）
const roundIdx = ref(0)           // 当前选中轮次索引（records 下标，默认最新）
const data = ref(null)            // 当前轮次诊断数据
const noAgent = ref(false)        // Agent 未就绪
const noData = ref(false)         // 暂无数据

/** 被 Stage1 筛选通过的新闻索引集合 */
const selectedSet = ref(new Set())

/** 判断某条新闻是否通过 Stage1 筛选 */
function isSelected(i) {
  return selectedSet.value.has(i)
}

/** 切换轮次后应用选中记录 */
function applyRound() {
  const r = records.value[roundIdx.value]
  data.value = r || null
  noAgent.value = false
  noData.value = !r
  selectedSet.value = new Set(r ? r.selected_idx || [] : [])
}

/** 格式化时间为 HH:mm:ss */
function formatTime(t) {
  if (!t) return '-'
  const d = new Date(t)
  return d.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
}

/** 从后端加载全量 LLM/Stage 轮次记录，默认展示最新一轮 */
async function loadData() {
  loading.value = true
  try {
    const res = await api.fetchStageRecords()
    if (res.status === 'no_engine') {
      noAgent.value = true
      noData.value = false
      records.value = []
      data.value = null
    } else if (!Array.isArray(res) || res.length === 0) {
      noData.value = true
      noAgent.value = false
      records.value = []
      data.value = null
    } else {
      records.value = res
      roundIdx.value = 0
      applyRound()
    }
  } catch (e) {
    console.error('LLMDebug 加载失败', e)
  } finally {
    loading.value = false
  }
}

onMounted(loadData)
</script>

<style scoped>
.llm-debug-page { max-width: 960px; margin: 0 auto; }
.page-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 14px; }
.page-header h2 { font-size: 18px; }
.header-right { display: flex; align-items: center; gap: 10px; }
.round-select {
  padding: 6px 10px; border-radius: 6px; border: 1px solid #333;
  background: #1a1a2e; color: #ccc; font-size: 12px; cursor: pointer; max-width: 320px;
}
.btn-refresh { padding: 6px 14px; border-radius: 6px; border: 1px solid #FF4D4F; background: transparent; color: #FF4D4F; font-size: 13px; cursor: pointer; }
.btn-refresh:disabled { opacity: 0.5; }
.btn-refresh:hover { background: rgba(255,77,79,0.1); }

.empty { text-align: center; padding: 40px; color: #666; font-size: 14px; }

.summary-bar { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 20px; background: #1a1a2e; border-radius: 8px; padding: 12px 16px; }
.summary-item { display: flex; flex-direction: column; gap: 2px; min-width: 80px; }
.summary-label { font-size: 11px; color: #888; }
.summary-value { font-size: 16px; font-weight: 600; color: #e0e0e0; }
.tag-llm { color: #4caf50; }
.tag-keyword { color: #ff9800; }

.section-title { font-size: 15px; margin-bottom: 10px; color: #ccc; border-bottom: 1px solid #2a2a3e; padding-bottom: 6px; }

.stage1-list { margin-bottom: 24px; }
.title-item { display: flex; align-items: center; gap: 8px; padding: 6px 10px; border-radius: 4px; margin-bottom: 2px; font-size: 13px; }
.title-item.selected { background: rgba(76,175,80,0.08); }
.title-item.discarded { opacity: 0.45; }
.title-idx { color: #666; min-width: 24px; font-size: 11px; text-align: right; }
.title-text { flex: 1; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.title-badge { font-size: 11px; padding: 1px 6px; border-radius: 3px; white-space: nowrap; }
.badge-pass { background: rgba(76,175,80,0.2); color: #4caf50; }
.badge-skip { background: rgba(255,152,0,0.15); color: #ff9800; }

.stage2-events { display: flex; flex-direction: column; gap: 10px; margin-bottom: 20px; }
.event-card { background: #1a1a2e; border-radius: 8px; padding: 12px 14px; border: 1px solid #2a2a3e; }
.event-header { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; flex-wrap: wrap; }
.event-title { flex: 1; font-size: 14px; font-weight: 600; color: #e0e0e0; min-width: 0; }
.event-score { font-size: 12px; color: #888; white-space: nowrap; }

.tag { font-size: 11px; padding: 2px 7px; border-radius: 4px; white-space: nowrap; }
.tag-利好 { background: rgba(76,175,80,0.2); color: #4caf50; }
.tag-利空 { background: rgba(255,77,79,0.2); color: #FF4D4F; }
.tag-中性 { background: rgba(255,152,0,0.15); color: #ff9800; }

.event-body { display: flex; flex-direction: column; gap: 5px; }
.event-row { display: flex; align-items: flex-start; gap: 8px; font-size: 12px; }
.event-label { color: #888; min-width: 32px; flex-shrink: 0; }
.event-tags { display: flex; flex-wrap: wrap; gap: 4px; }
.mini-tag { font-size: 11px; padding: 1px 6px; border-radius: 3px; background: #2a2a3e; color: #aaa; }
.mini-tag.sector { color: #64b5f6; background: rgba(100,181,246,0.1); }
.mini-tag.stock { color: #ff9800; background: rgba(255,152,0,0.1); }
.mini-tag.impact-高 { color: #FF4D4F; background: rgba(255,77,79,0.15); }
.mini-tag.impact-中 { color: #ff9800; background: rgba(255,152,0,0.12); }
.mini-tag.impact-低 { color: #888; background: #2a2a3e; }
.event-reason { color: #aaa; line-height: 1.4; }
</style>
