// web/src/pages/Quant.vue
<template>
  <div class="quant-page">
    <div class="page-title">📈 量化交易</div>
    <div class="page-sub">实盘链路参数、仓位纪律与战法白名单（保存后约 5 秒热加载生效）</div>

    <!-- ── 实盘互通健康条：首尔→广州探测 + 广州回报新鲜度（10s 轮询）── -->
    <div class="card link-card">
      <template v-if="state && state.enabled">
        <span class="dot" :class="state.last_probe_ok ? 'ok' : 'bad'">●</span>
        <span>首尔 ↔ 广州</span>
        <span class="mono">{{ state.gateway_url }}</span>
        <span v-if="state.last_latency_ms > 0" class="pill">{{ state.last_latency_ms }}ms</span>
        <span :class="['pill', state.tripped ? 'warn' : 'good']">
          {{ state.tripped ? '熔断:' + (state.trip_reason || '未知') : '正常' }}
        </span>
        <span>{{ state.mode === 'auto' ? '自动' : '手动' }}</span>
        <span v-if="fmtAgo(state.last_report_at)">回报{{ fmtAgo(state.last_report_at) }}</span>
      </template>
      <template v-else>
        <span class="dot bad">●</span><span>实盘链路未启用</span>
        <span class="hint">打开下方「总开关」并配置网关地址后开始互通</span>
      </template>
    </div>

    <!-- ── 总开关与执行方式 ── -->
    <div class="card">
      <div class="card-header">总开关与执行方式</div>
      <div class="form-row switch-row">
        <label class="lbl">实盘总开关</label>
        <label class="switch">
          <input type="checkbox" v-model="form.enabled" @change="saveSwitches" />
          <span class="slider"></span>
        </label>
        <span class="hint">关闭后引擎不再向网关传递任何信号/建议（纸面盘不受影响）</span>
      </div>
      <div class="form-row">
        <label class="lbl">执行模式</label>
        <button :class="['seg', form.mode === 'manual' ? 'on' : '']" @click="form.mode = 'manual'">手动确认</button>
        <button :class="['seg', form.mode === 'auto' ? 'on' : '']" @click="form.mode = 'auto'">全自动</button>
        <span class="hint">手动=每单前端确认；自动=信号直接下单</span>
      </div>
      <div class="form-row">
        <label class="lbl">委托价格</label>
        <button :class="['seg', form.price_type === 'market' ? 'on' : '']" @click="form.price_type = 'market'">对手价</button>
        <button :class="['seg', form.price_type === 'limit' ? 'on' : '']" @click="form.price_type = 'limit'">限价</button>
      </div>
      <div class="form-row switch-row">
        <label class="lbl">自动卖出</label>
        <label class="switch">
          <input type="checkbox" v-model="form.auto_sell" />
          <span class="slider"></span>
        </label>
        <span class="hint">自动模式下止损/清仓级建议自动全仓卖出；止盈/减仓保持提醒</span>
      </div>
      <div class="form-row">
        <label class="lbl">心跳超时(秒)</label>
        <input class="inp short" type="number" v-model.number="form.miss_heartbeat_sec" min="30" max="3600" />
        <span class="hint">连续失联超过该值触发熔断暂停下单（30-3600）</span>
      </div>
      <div class="form-row">
        <label class="lbl">网关地址</label>
        <input class="inp wide mono" v-model.trim="form.gateway_url" placeholder="http://81.71.69.17:8789" />
      </div>
      <div class="form-row">
        <label class="lbl">鉴权Token</label>
        <input class="inp wide mono" type="password" v-model.trim="tokenInput" :placeholder="form.token_masked || '未设置'" />
        <span class="hint">显示为脱敏形态；留空表示保持原值不变</span>
      </div>
      <div class="save-bar">
        <button class="btn-save" @click="saveExec" :disabled="saving">{{ saving ? '保存中…' : '保存执行参数' }}</button>
      </div>
    </div>

    <!-- ── 仓位纪律 ── -->
    <div class="card">
      <div class="card-header">仓位纪律</div>
      <div class="form-grid">
        <div class="field"><label>最大持仓数</label><input class="inp" type="number" v-model.number="form.max_positions" min="1" max="50" /><span class="hint">1-50，双端校验</span></div>
        <div class="field"><label>单票金额(元)</label><input class="inp" type="number" v-model.number="form.fixed_amount" min="0" step="500" /><span class="hint">每次买入投入金额</span></div>
        <div class="field"><label>初始资金(元)</label><input class="inp" type="number" v-model.number="form.initial_capital" min="0" step="10000" /><span class="hint">用于仓位约束预检</span></div>
        <div class="field"><label>单日买入笔数上限</label><input class="inp" type="number" v-model.number="form.daily_max_buys" min="0" /><span class="hint">0=不设限，防信号风暴</span></div>
        <div class="field"><label>单日买入预算(元)</label><input class="inp" type="number" v-model.number="form.daily_budget_amount" min="0" step="10000" /><span class="hint">0=不设限，超出拒绝新买入</span></div>
      </div>
      <div class="save-bar">
        <button class="btn-save" @click="saveCaps" :disabled="saving">{{ saving ? '保存中…' : '保存仓位纪律' }}</button>
      </div>
    </div>

    <!-- ── 战法白名单 ── -->
    <div class="card">
      <div class="card-header">战法开关
        <span class="card-sub">关闭的战法信号不会进入实盘链路（模拟盘不受影响）；全部开启 = 不设白名单</span>
      </div>
      <div v-for="s in strategyRows" :key="s.value" class="strategy-row">
        <div>
          <div class="st-name">{{ s.label }}</div>
          <div class="st-code">{{ s.value }}</div>
        </div>
        <div class="st-amount">
          <input class="inp short" type="number" min="0" step="500" v-model="amountsInput[s.value]" placeholder="全局" />
          <span class="hint">元/次</span>
        </div>
        <label class="switch">
          <input type="checkbox" v-model="strategyOn[s.value]" @change="markStrategyDirty" />
          <span class="slider"></span>
        </label>
      </div>
      <div class="save-bar">
        <span class="hint">{{ strategyHint }} · 仓位留空/0 = 使用全局单票金额</span>
        <button class="btn-save" :disabled="!strategyDirty || saving" @click="saveStrategies">
          {{ saving ? '保存中…' : (strategyDirty ? '保存战法开关 *' : '已同步') }}
        </button>
      </div>
    </div>

    <!-- ── 交易流水与整体盈亏 ── -->
    <div class="card">
      <div class="card-header">交易流水与整体盈亏
        <span class="card-sub">已实现=加权成本重放；浮动=市值-成本×数量；30s 刷新</span>
      </div>
      <template v-if="trades">
        <div class="chips">
          <div class="chip" :class="(trades.summary.total_pnl || 0) >= 0 ? 'up' : 'down'">
            <div class="chip-num">{{ fmtMoney(trades.summary.total_pnl) }}</div>
            <div class="chip-lbl">总盈亏</div>
          </div>
          <div class="chip">
            <div class="chip-num" :class="(trades.summary.realized_pnl || 0) >= 0 ? 'up' : 'down'">{{ fmtMoney(trades.summary.realized_pnl) }}</div>
            <div class="chip-lbl">已实现</div>
          </div>
          <div class="chip">
            <div class="chip-num" :class="(trades.summary.unrealized_pnl || 0) >= 0 ? 'up' : 'down'">{{ fmtMoney(trades.summary.unrealized_pnl) }}</div>
            <div class="chip-lbl">浮动盈亏</div>
          </div>
          <div class="chip"><div class="chip-num">{{ trades.summary.trade_count }}</div><div class="chip-lbl">成交笔数</div></div>
          <div class="chip"><div class="chip-num">{{ trades.summary.wins }}胜 / {{ trades.summary.losses }}负</div><div class="chip-lbl">卖出胜负</div></div>
        </div>

        <table v-if="(trades.by_strategy || []).length" class="tbl">
          <thead><tr><th>战法</th><th>买入额</th><th>卖出额</th><th>已实现盈亏</th><th>笔数</th></tr></thead>
          <tbody>
            <tr v-for="st in trades.by_strategy" :key="st.strategy">
              <td>{{ st.strategy }}</td><td>{{ st.buys }}</td><td>{{ st.sells }}</td>
              <td :class="st.realized_pnl >= 0 ? 'up' : 'down'">{{ fmtMoney(st.realized_pnl) }}</td>
              <td>{{ st.trade_count }}</td>
            </tr>
          </tbody>
        </table>
        <p v-else class="hint empty-tip">暂无成交——实盘成交后此处出现按战法归因的盈亏统计（飞轮回流数据源）</p>

        <table v-if="(trades.fills || []).length" class="tbl fills-tbl">
          <thead><tr><th>时间</th><th>代码</th><th>方向</th><th>价格</th><th>数量</th><th>金额</th><th>战法</th></tr></thead>
          <tbody>
            <tr v-for="(f, i) in trades.fills" :key="f.order_id + f.traded_at + i">
              <td class="mono">{{ (f.traded_at || '').replace('T', ' ').slice(5, 19) }}</td>
              <td class="mono">{{ f.code }}</td>
              <td :class="f.side === '买入' ? 'up' : 'down'">{{ f.side }}</td>
              <td>{{ f.price }}</td><td>{{ f.qty }}</td><td>{{ f.amount }}</td>
              <td class="mono dim">{{ f.strategy }}</td>
            </tr>
          </tbody>
        </table>
      </template>
      <p v-else class="hint">加载交易流水…</p>
    </div>
  </div>
</template>

<script setup>
// Quant.vue — 量化交易页：实盘链路状态展示 + 总开关/执行方式 + 仓位纪律 + 战法白名单。
// 数据面：GET /api/qmt/state（互通快照）、GET/POST /api/config/qmt（账号级配置，局部合并保存，
// token 脱敏回显——提交空串或哨兵即保持原值）。后端校验枚举/范围，5s 热加载生效。
import { ref, reactive, computed, onMounted, onUnmounted } from 'vue'
import * as api from '../api/index.js'

const KNOWN_STRATEGIES = [
  { value: 'dragon', label: '龙头战法 Dragon' },
  { value: 'double_bump', label: '双响炮 DoubleBump' },
  { value: 'n_shape', label: 'N形超短 NShape' },
  { value: 'dragon_return', label: '龙回头(中线) DragonReturn' },
]

const state = ref(null)                       // /api/qmt/state 互通快照
const form = reactive({                       // 表单（GET 回填）
  enabled: false, mode: 'manual', price_type: 'market', auto_sell: false,
  gateway_url: '', token_masked: '',
  fixed_amount: 10000, max_positions: 10, initial_capital: 100000,
  daily_max_buys: 20, daily_budget_amount: 100000, miss_heartbeat_sec: 120,
})
const tokenInput = ref('')                    // token 输入框（留空=不改）
const knownStrategies = ref([...KNOWN_STRATEGIES.map(s => s.value)])
const strategyOn = reactive({})               // 战法勾选态
const strategyDirty = ref(false)              // 白名单有未保存改动
const saving = ref(false)
const savedFlash = ref('')
const trades = ref(null)                      // /api/qmt/trades 流水+盈亏（30s 轮询）
const amountsInput = reactive({})             // 每战法仓位大小输入（空串/0=使用全局 fixed_amount）
let stateTimer = null
let tradesTimer = null

const strategyRows = computed(() =>
  KNOWN_STRATEGIES.filter(s => knownStrategies.value.includes(s.value)))

// 白名单语义：数组为空 = 全部允许。全开时提交 []；部分开启时提交勾选集合。
/** 白名单勾选语义：数组为空=全部允许；部分开启=白名单精确集合 */
const allStrategyOn = computed(() => strategyRows.value.every(s => strategyOn[s.value]))
const strategyHint = computed(() => {
  const onCount = strategyRows.value.filter(s => strategyOn[s.value]).length
  if (allStrategyOn.value) return '当前：全部允许'
  return `当前：${onCount}/${strategyRows.value.length} 允许进入实盘`
})

/** GET 配置回填表单与战法勾选态 */
async function loadConfig() {
  const c = await api.fetchQMTConfig()
  Object.assign(form, {
    enabled: !!c.enabled, mode: c.mode || 'manual', price_type: c.price_type || 'market',
    auto_sell: !!c.auto_sell, gateway_url: c.gateway_url || '', token_masked: c.token_masked || '',
    fixed_amount: c.fixed_amount ?? 10000, max_positions: c.max_positions ?? 10,
    initial_capital: c.initial_capital ?? 100000,
    daily_max_buys: c.daily_max_buys ?? 20, daily_budget_amount: c.daily_budget_amount ?? 100000,
    miss_heartbeat_sec: c.miss_heartbeat_sec ?? 120,
  })
  if (Array.isArray(c.known_strategies) && c.known_strategies.length) knownStrategies.value = c.known_strategies
  // 勾选态推导：白名单为空=全开；否则按包含关系
  const wl = Array.isArray(c.strategies) ? c.strategies : []
  for (const v of knownStrategies.value) strategyOn[v] = wl.length === 0 || wl.includes(v)
  // 每战法仓位大小回填（未配置显示空串=全局）
  const sa = c.strategy_amounts || {}
  for (const v of knownStrategies.value) amountsInput[v] = sa[v] ?? ''
  strategyDirty.value = false
}

/** 拉取交易流水与盈亏 */
async function loadTrades() {
  try { trades.value = await api.fetchQMTTrades() } catch (e) { /* 忽略，保留上次数据 */ }
}

/** 盈亏金额格式化：带符号两位小数 */
function fmtMoney(v) {
  const n = Number(v) || 0
  return (n > 0 ? '+' : '') + n.toFixed(2)
}

/** 拉取互通健康快照（10s 轮询） */
async function loadState() {
  try { state.value = await api.fetchQMTState() } catch (e) { /* 忽略 */ }
}

function markStrategyDirty() { strategyDirty.value = true }

/** 通用保存：patch 提交 → 成功后重拉配置回填（含脱敏 token 刷新） */
async function patch(fields, okTip) {
  saving.value = true
  try {
    await api.updateQMTConfig(fields)
    savedFlash.value = okTip || '已保存'
    setTimeout(() => { savedFlash.value = '' }, 2000)
    await loadConfig()
  } catch (e) {
    alert('保存失败：' + (e && e.message ? e.message : e))
  } finally {
    saving.value = false
  }
}

// 总开关切换即时生效：开启需二次确认（高危操作面）
/** 总开关保存：开启实盘链路属高危操作，需二次确认；关闭立即停传信号（纸面盘不受影响） */
async function saveSwitches() {
  if (form.enabled && !window.confirm('确认启用实盘链路？启用后将按下方参数向广州网关传递真实交易指令。')) {
    form.enabled = false
    return
  }
  await patch({ enabled: form.enabled }, form.enabled ? '实盘链路已启用' : '实盘链路已停用')
}

/** 执行参数保存：mode/price_type/auto_sell/心跳/网关地址/token（留空=保持原值）；切全自动需确认 */
async function saveExec() {
  if (form.mode === 'auto' &&
      !window.confirm('确认切换为「全自动」？信号将不经人工确认直接下单（受熔断/纪律约束）。')) {
    form.mode = 'manual'
    return
  }
  const fields = {
    mode: form.mode, price_type: form.price_type, auto_sell: form.auto_sell,
    gateway_url: form.gateway_url, miss_heartbeat_sec: form.miss_heartbeat_sec,
  }
  if (tokenInput.value) fields.token = tokenInput.value   // 留空=保持原值
  await patch(fields, '执行参数已保存')
}

/** 仓位纪律保存：最大持仓/单票金额/初始资金/单日笔数与预算（后端做范围校验） */
async function saveCaps() {
  await patch({
    max_positions: form.max_positions, fixed_amount: form.fixed_amount,
    initial_capital: form.initial_capital, daily_max_buys: form.daily_max_buys,
    daily_budget_amount: form.daily_budget_amount,
  }, '仓位纪律已保存')
}

/** 战法开关+每战法仓位大小保存：全部勾选→提交空白名单（=全部允许）；仓位仅提交 >0 覆盖项 */
function saveStrategies() {
  const values = strategyRows.value.filter(s => strategyOn[s.value]).map(s => s.value)
  // 每战法仓位大小：仅提交 >0 的覆盖项；全部勾选 → strategies 提交空数组（= 不设白名单）
  const amounts = {}
  for (const v of knownStrategies.value) {
    const n = parseFloat(amountsInput[v])
    if (!Number.isNaN(n) && n > 0) amounts[v] = n
  }
  // 失败时 loadConfig 会重置勾选态
  return patch(
    { strategies: allStrategyOn.value ? [] : values, strategy_amounts: amounts },
    '战法开关与仓位已保存',
  )
}

onMounted(async () => {
  loadState()
  stateTimer = setInterval(loadState, 10000)
  loadTrades()
  tradesTimer = setInterval(loadTrades, 30000)
  try { await loadConfig() } catch (e) { alert('加载实盘配置失败：' + (e && e.message ? e.message : e)) }
})
onUnmounted(() => {
  if (stateTimer) clearInterval(stateTimer)
  if (tradesTimer) clearInterval(tradesTimer)
})
</script>

<style scoped>
.quant-page { max-width: 900px; }
.page-title { font-size: 20px; font-weight: 700; margin-bottom: 4px; }
.page-sub { font-size: 12px; color: #888; margin-bottom: 14px; }

.link-card { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; font-size: 13px; padding: 12px 14px; margin-bottom: 14px; }
.dot { font-size: 16px; line-height: 1; }
.dot.ok { color: #4caf50; }
.dot.bad { color: #666; }
.mono { font-family: monospace; color: #4fc3f7; }
.pill { font-size: 11px; padding: 2px 8px; border-radius: 10px; background: rgba(255,255,255,0.08); }
.pill.good { color: #4caf50; background: rgba(76,175,80,0.15); }
.pill.warn { color: #FF4D4F; background: rgba(255,77,79,0.15); }

.card { background: #1a1a2e; border-radius: 8px; padding: 14px; margin-bottom: 14px; }
.card-header { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; font-size: 13px; font-weight: 600; color: #ccc; margin-bottom: 12px; }
.card-sub { font-size: 11px; color: #666; font-weight: 400; }

.form-row { display: flex; align-items: center; gap: 10px; padding: 7px 0; flex-wrap: wrap; }
.lbl { width: 110px; flex-shrink: 0; font-size: 13px; color: #aaa; text-align: right; }
.hint { font-size: 11px; color: #666; }
.inp { background: #12121e; border: 1px solid #2a2a3e; border-radius: 6px; color: #e0e0e0; padding: 6px 9px; font-size: 13px; }
.inp:focus { outline: none; border-color: #b388ff; }
.inp.short { width: 90px; }
.inp.wide { flex: 1; min-width: 240px; }
.form-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; }
.field { display: flex; flex-direction: column; gap: 5px; }
.field label { font-size: 12px; color: #aaa; }
.field .hint { font-size: 10px; }

.seg { background: transparent; border: 1px solid #2a2a3e; color: #999; border-radius: 6px; padding: 5px 14px; font-size: 12px; cursor: pointer; }
.seg.on { border-color: #b388ff; color: #b388ff; background: rgba(179,136,255,0.1); }

.switch { position: relative; width: 40px; height: 22px; flex-shrink: 0; }
.switch input { opacity: 0; width: 0; height: 0; }
.slider { position: absolute; cursor: pointer; inset: 0; background: #33334a; border-radius: 22px; transition: 0.2s; }
.slider::before { content: ''; position: absolute; height: 16px; width: 16px; left: 3px; top: 3px; background: #888; border-radius: 50%; transition: 0.2s; }
.switch input:checked + .slider { background: rgba(179,136,255,0.35); }
.switch input:checked + .slider::before { transform: translateX(18px); background: #b388ff; }

.strategy-row { display: flex; align-items: center; justify-content: space-between; gap: 10px; padding: 9px 4px; border-bottom: 1px solid #22223a; }
.strategy-row:last-of-type { border-bottom: none; }
.st-name { font-size: 13px; color: #ddd; }
.st-code { font-family: monospace; font-size: 11px; color: #555; margin-top: 2px; }
.st-amount { display: flex; align-items: center; gap: 6px; flex: 1; justify-content: flex-end; }

.chips { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 10px; margin-bottom: 12px; }
.chip { background: #12121e; border-radius: 8px; padding: 10px; text-align: center; }
.chip-num { font-size: 18px; font-weight: 700; color: #e0e0e0; font-family: monospace; }
.chip-lbl { font-size: 11px; color: #777; margin-top: 3px; }
.up { color: #FF4D4F; }
.down { color: #4caf50; }

.tbl { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 8px; }
.tbl th { text-align: left; color: #666; font-weight: 600; padding: 5px 6px; border-bottom: 1px solid #2a2a3e; }
.tbl td { padding: 5px 6px; border-bottom: 1px solid #1a1a26; color: #ccc; }
.tbl tr:last-child td { border-bottom: none; }
.mono { font-family: monospace; }
.dim { color: #666; }
.empty-tip { padding: 8px 2px; }

.save-bar { display: flex; align-items: center; gap: 12px; justify-content: flex-end; margin-top: 10px; }
.btn-save { background: #b388ff; color: #14101e; border: none; border-radius: 6px; padding: 7px 16px; font-size: 13px; font-weight: 600; cursor: pointer; }
.btn-save:disabled { opacity: 0.45; cursor: default; }
.btn-save:not(:disabled):hover { filter: brightness(1.1); }
@media (max-width: 768px) { .lbl { text-align: left; width: 100%; } .form-grid { grid-template-columns: 1fr; } }
</style>

// web/src/pages/Quant.jsx
// ── 量化交易页 Quant.jsx ──
// 页面用途：实盘链路总开关、执行方式、仓位纪律与战法白名单的统一管理界面。
// 主要功能：查看首尔↔广州链路状态/熔断；配置总开关、执行模式、委托价格、心跳超时、网关与 Token；
//          设定最大持仓/单票金额/预算等仓位纪律；按战法开关实盘准入并展示交易流水与归因盈亏。
//          定时轮询：链路状态 10s 一次、交易流水 30s 一次；保存后约 5s 热加载生效。
// 使用 TDesign React 组件（Card / Form / Input / Button / Tag / Table）。
import React, { useState, useEffect, useRef, useMemo } from 'react'
import ToggleSw from '../components/ToggleSw'
import { Card, Form, Input, Button, Tag, Table, MessagePlugin, DialogPlugin } from 'tdesign-react'
import * as api from '../api/index.js'

// 战法分组标签：form=内置形态战法、factor=因子战法、pattern=形态自动发现战法。
// 后端 /api/config/qmt 的 known_strategies 为 [{id,name,kind}]；因子/形态战法审批注入后自动出现。
const KIND_LABELS = {
  form: '形态战法（内置）',
  factor: '因子战法',
  pattern: '形态自动发现战法',
}
const KIND_ORDER = ['form', 'factor', 'pattern']

// 本地缓存键：切换 tab 时先显示上次成功加载的配置，避免开关/参数瞬间跳回默认值。
// 键含当前账号名（多账号隔离），防止 A 账号的表单缓存串给 B 账号显示。
const STORAGE_QMT_FORM_BASE = 'liangzai_qmt_form'

function cachedFormKey() {
  const acc = (typeof api.getAccount === 'function' && api.getAccount()) || ''
  return acc ? STORAGE_QMT_FORM_BASE + ':' + acc : STORAGE_QMT_FORM_BASE
}

function readCachedForm() {
  try {
    const raw = localStorage.getItem(cachedFormKey()) || localStorage.getItem(STORAGE_QMT_FORM_BASE)
    if (raw) return JSON.parse(raw)
  } catch (_) {}
  return null
}

function writeCachedForm(form) {
  try {
    localStorage.setItem(cachedFormKey(), JSON.stringify(form))
  } catch (_) {}
}

// 涨跌配色（红涨绿跌）：盈亏 >=0 用红色，<0 用绿色
function pnlColor(v) {
  return (v || 0) >= 0 ? '#e34d59' : '#00a870'
}

// 通用确认弹窗：返回 Promise<boolean>，用户确认 resolve(true)、关闭/取消 resolve(false)。
// 必须只 resolve 一次：TDesign 的 d.hide() 会同步触发 onClose，若 onConfirm 先 d.hide() 再 resolve(true)，
// onClose 的 resolve(false) 会先一步生效（Promise 首次 resolve 即定型），导致"确认"被当作"取消"——
// 表现为实盘总开关点了启用却存不进、瞬间弹回关闭。这里用 done 守卫保证首次 resolve 的值生效。
// English: resolve-once guard. d.hide() synchronously fires onClose; without the guard a confirm could
// resolve false (treated as cancel), so enabling the master switch would never persist.
function confirmDialog(body, header = '确认') {
  return new Promise((resolve) => {
    let done = false
    const finish = (val) => {
      if (done) return
      done = true
      d.hide()
      resolve(val)
    }
    const d = DialogPlugin.confirm({
      header,
      body,
      theme: 'warning',
      onConfirm: () => finish(true),
      onClose: () => finish(false),
    })
  })
}

/**
 * 量化交易主页面组件。
 * state：链路运行状态（enabled / 心跳 / 延迟 / 熔断等）。
 * form：实盘链路与仓位纪律的可编辑表单数据（保存时整体回写后端）。
 * tokenInput：鉴权 Token 明文输入，留空表示沿用原值。
 * knownStrategies：后端已知的全部战法标识列表。
 * strategyOn：各战法是否允许进入实盘的开关映射。
 * strategyDirty：战法开关是否被改动（控制保存按钮可用性）。
 * saving：保存中标志（禁用按钮、防重复提交）。
 * trades：交易流水与整体/分战法盈亏汇总。
 * amountsInput：各战法自定义单票金额（留空则用全局 fixed_amount）。
 * 副作用：挂载时拉取配置/状态/流水，并以定时器轮询刷新。
 */
export default function Quant() {
  const [state, setState] = useState(null)
  const cachedForm = readCachedForm()
  const [form, setForm] = useState(cachedForm || {
    enabled: false, mode: 'manual', price_type: 'market', auto_sell: false,
    gateway_url: '', token_masked: '',
    fixed_amount: 10000, max_positions: 10, initial_capital: 100000,
    daily_max_buys: 20, daily_budget_amount: 100000, miss_heartbeat_sec: 120,
  })
  const [tokenInput, setTokenInput] = useState('')
  const [strategyList, setStrategyList] = useState([])
  const [strategyOn, setStrategyOn] = useState({})
  const [strategyDirty, setStrategyDirty] = useState(false)
  const [saving, setSaving] = useState(false)
  const [trades, setTrades] = useState(null)
  const [amountsInput, setAmountsInput] = useState({})
  // 配置加载失败提示：加载失败时表单停留在本地缓存值，若无提示用户会误把
  // 缓存当成服务器真实状态，误以为"开关被自动关闭"。显式告警消除歧义。
  const [loadErr, setLoadErr] = useState('')
  // 后端鉴权拒绝（403）：量化交易仅管理员可访问，后端据此决定，前端只负责展示。
  // English: backend denied (403) — quant trading is admin-only; the frontend just renders the denial.
  const [forbidden, setForbidden] = useState(false)
  // 是否已从服务器同步完成：首屏先显示「同步中」占位，避免把本地缓存的旧值
  // 误当成服务器真实状态（用户反馈「开关刷新后变回关闭」多源于此闪烁）。
  // English: whether config has synced from server; show a placeholder first paint
  // so a stale cached value can never be mistaken for the server's truth.
  const [syncing, setSyncing] = useState(true)

  const stateTimer = useRef(null)
  const tradesTimer = useRef(null)

  // 按 kind 分组（form → factor → pattern），便于分别展示"形态战法 / 因子战法"
  const strategyGroups = useMemo(() => {
    const g = { form: [], factor: [], pattern: [] }
    strategyList.forEach((s) => {
      const k = g[s.kind] ? s.kind : 'form'
      g[k].push(s)
    })
    return KIND_ORDER.map((kind) => ({ kind, label: KIND_LABELS[kind] || kind, items: g[kind] })).filter((x) => x.items.length)
  }, [strategyList])
  const allStrategyOn = useMemo(() => strategyList.length > 0 && strategyList.every((s) => strategyOn[s.id]), [strategyList, strategyOn])
  const strategyHint = useMemo(() => {
    const onCount = strategyList.filter((s) => strategyOn[s.id]).length
    if (allStrategyOn) return '当前：全部允许'
    return `当前：${onCount}/${strategyList.length} 允许进入实盘`
  }, [strategyList, strategyOn, allStrategyOn])

  // 金额格式化：正数补 + 号并保留两位小数
  function fmtMoney(v) {
    const n = Number(v) || 0
    return (n > 0 ? '+' : '') + n.toFixed(2)
  }
  // 将时间戳格式化为「x秒前 / x分前 / x小时前」。
  // 兼容两种来源：后端 time.Time 默认序列化为 RFC3339 字符串（如 "2026-08-28T00:01:01Z"），
  // 也可能是 Unix 秒级数字；统一归一后再计算，避免字符串做乘法得到 NaN。
  function fmtAgo(ts) {
    if (!ts) return ''
    let sec
    if (typeof ts === 'string') {
      const d = new Date(ts)
      if (isNaN(d.getTime())) return ''
      sec = Math.floor((Date.now() - d.getTime()) / 1000)
    } else {
      sec = Math.floor((Date.now() - ts * 1000) / 1000)
    }
    if (isNaN(sec) || sec < 0) return ''
    if (sec < 60) return sec + '秒前'
    if (sec < 3600) return Math.floor(sec / 60) + '分前'
    return Math.floor(sec / 3600) + '小时前'
  }

  // 拉取实盘配置并回填表单/战法开关/自定义金额；白名单为空数组时默认全部开启。
  // 失败时置 loadErr 告警（页面顶部显示），并向上抛出由调用方决定是否 toast。
  async function loadConfig() {
    setSyncing(true)
    try {
      const c = await api.fetchQMTConfig()
      setLoadErr('')
      const nextForm = {
        enabled: !!c.enabled, mode: c.mode || 'manual', price_type: c.price_type || 'market',
        auto_sell: !!c.auto_sell, gateway_url: c.gateway_url || '', token_masked: c.token_masked || '',
        fixed_amount: c.fixed_amount ?? 10000, max_positions: c.max_positions ?? 10,
        initial_capital: c.initial_capital ?? 100000,
        daily_max_buys: c.daily_max_buys ?? 20, daily_budget_amount: c.daily_budget_amount ?? 100000,
        miss_heartbeat_sec: c.miss_heartbeat_sec ?? 120,
      }
      setForm(nextForm)
      writeCachedForm(nextForm)
      // 后端 known_strategies 可能为对象数组 [{id,name,kind}]（新）或纯 ID 数组（旧），统一归一
      let list = []
      if (Array.isArray(c.known_strategies)) {
        list = c.known_strategies.map((x) => {
          if (typeof x === 'string') return { id: x, name: x, kind: 'form' }
          return { id: x.id, name: x.name || x.id, kind: x.kind || 'form' }
        })
      }
      setStrategyList(list)
      const wl = Array.isArray(c.strategies) ? c.strategies : []
      const on = {}
      list.forEach((v) => { on[v.id] = wl.length === 0 || wl.includes(v.id) })
      setStrategyOn(on)
      const sa = c.strategy_amounts || {}
      const ai = {}
      list.forEach((v) => { ai[v.id] = sa[v.id] ?? '' })
      setAmountsInput(ai)
      setStrategyDirty(false)
      setSyncing(false)
    } catch (e) {
      // 后端返回 403（无权限）时，直接展示「无权限」面板，不再走缓存兜底提示。
      if (e && e.message && e.message.indexOf('无权限') >= 0) {
        setForbidden(true)
        setSyncing(false)
        return
      }
      setLoadErr('实盘配置加载失败（' + (e && e.message ? e.message : '网络异常') + '）——下方开关显示的是本机缓存，不代表服务器真实状态')
      setSyncing(false)
      throw e
    }
  }

  // 拉取交易流水（含汇总与分战法/成交流水），仅在返回合法时更新
  async function loadTrades() {
    try {
      const t = await api.fetchQMTTrades()
      if (t && t.summary) setTrades(t)
    } catch (_) {}
  }

  // 拉取链路运行状态（心跳/延迟/熔断等）
  async function loadState() {
    try { setState(await api.fetchQMTState()) } catch (_) {}
  }

  // 标记战法开关被改动
  function markStrategyDirty() { setStrategyDirty(true) }

  // 通用保存：回写指定字段到后端，成功提示并重新拉取配置。
  // 失败时除提示外，还回滚到后端真实配置——否则界面显示与实际不一致，
  // 刷新/切tab重新挂载后配置"跳回"，造成开关丢了的现象。
  async function patch(fields, okTip) {
    setSaving(true)
    try {
      await api.updateQMTConfig(fields)
      MessagePlugin.success(okTip || '已保存')
      await loadConfig()
    } catch (e) {
      MessagePlugin.error('保存失败：' + (e && e.message ? e.message : e))
      try { await loadConfig() } catch (_) {}
    } finally {
      setSaving(false)
    }
  }

  // 切换执行模式：点击立即保存到后端（全自动需二次确认），不再依赖"保存"按钮
  async function saveMode(mode) {
    if (saving) return
    if (mode === 'auto' && !(await confirmDialog('确认切换为「全自动」？信号将不经人工确认直接下单（受熔断/纪律约束）。', '切换全自动'))) return
    setForm((f) => ({ ...f, mode }))
    await patch({ mode }, mode === 'auto' ? '已切换为全自动' : '已切换为手动确认')
  }

  // 切换委托价格：点击立即保存到后端
  async function savePriceType(priceType) {
    if (saving) return
    setForm((f) => ({ ...f, price_type: priceType }))
    await patch({ price_type: priceType }, '委托价格已保存')
  }

  // 切换自动卖出：点击立即保存到后端
  async function saveAutoSell(v) {
    if (saving) return
    setForm((f) => ({ ...f, auto_sell: v }))
    await patch({ auto_sell: v }, v ? '已开启自动卖出' : '已关闭自动卖出')
  }

  // 保存实盘总开关：直接保存（不再用阻塞式二次确认，避免“开关一拨就弹回关闭”）。
  // 启用后下发真实交易指令属高危操作，故用非阻塞告警提示用户确认网关地址正确。
  // English: save immediately (no blocking confirm that could snap the switch back);
  // a non-blocking warning reminds the admin that enabling routes real orders to the gateway.
  async function saveSwitches(v) {
    if (saving) return
    await patch(
      { enabled: v },
      v
        ? '实盘链路已启用：将按下方参数向广州网关下发真实交易指令，请确认网关地址正确'
        : '实盘链路已停用',
    )
  }

  // 保存网关连接参数（网关地址/心跳超时/Token）；模式与价格已改为点击即存，不再随此保存
  async function saveExec() {
    const fields = {
      gateway_url: form.gateway_url, miss_heartbeat_sec: form.miss_heartbeat_sec,
    }
    if (tokenInput) fields.token = tokenInput
    await patch(fields, '网关连接参数已保存')
  }

  // 保存仓位纪律（最大持仓/单票金额/初始资金/日买笔数上限/日预算）
  async function saveCaps() {
    await patch({
      max_positions: form.max_positions, fixed_amount: form.fixed_amount,
      initial_capital: form.initial_capital, daily_max_buys: form.daily_max_buys,
      daily_budget_amount: form.daily_budget_amount,
    }, '仓位纪律已保存')
  }

  // 保存战法白名单与自定义金额：全部开启时传空数组表示不设白名单（含因子/形态战法）
  async function saveStrategies() {
    const values = strategyList.filter((s) => strategyOn[s.id]).map((s) => s.id)
    const amounts = {}
    for (const v of strategyList) {
      const n = parseFloat(amountsInput[v.id])
      if (!Number.isNaN(n) && n > 0) amounts[v.id] = n
    }
    return patch(
      { strategies: allStrategyOn ? [] : values, strategy_amounts: amounts },
      '战法开关与仓位已保存',
    )
  }

  useEffect(() => {
    loadState()
    // 链路状态每 10s 轮询一次（心跳/延迟/熔断实时性要求高）
    stateTimer.current = setInterval(loadState, 10000)
    loadTrades()
    // 交易流水每 30s 轮询一次（成交频率低，降低刷新压力）
    tradesTimer.current = setInterval(loadTrades, 30000)
    loadConfig().catch((e) => MessagePlugin.error('加载实盘配置失败：' + (e && e.message ? e.message : e)))
    // 卸载时清除两个定时器，防止内存泄漏与重复请求
    return () => {
      if (stateTimer.current) clearInterval(stateTimer.current)
      if (tradesTimer.current) clearInterval(tradesTimer.current)
    }
  }, [])

  // 执行模式 / 委托价格 的分段切换按钮样式工厂：active 为当前选中项（高饱和蓝，避免选中态过浅）
  const segBtn = (active) => ({
    marginRight: 8,
    padding: '5px 14px', borderRadius: 6, fontSize: 13, cursor: 'pointer',
    border: active ? '1px solid #1d4ed8' : '1px solid #cfd9ec',
    color: active ? '#ffffff' : '#5a6b86',
    background: active ? '#1d4ed8' : 'transparent',
    fontWeight: active ? 600 : 400,
  })

  // 分战法盈亏表列定义：realized_pnl 按涨跌配色渲染
  const byStrategyColumns = [
    { colKey: 'strategy', title: '战法', width: 140 },
    { colKey: 'buys', title: '买入额', width: 110 },
    { colKey: 'sells', title: '卖出额', width: 110 },
    {
      colKey: 'realized_pnl', title: '已实现盈亏', width: 120,
      cell: ({ row }) => <span style={{ color: pnlColor(row.realized_pnl) }}>{fmtMoney(row.realized_pnl)}</span>,
    },
    { colKey: 'trade_count', title: '笔数', width: 80 },
  ]

  // 成交流水表列定义：time 去掉 ISO 的 T 并截取至秒；side 买入红/卖出绿
  const fillsColumns = [
    { colKey: 'time', title: '时间', width: 130, cell: ({ row }) => (row.traded_at || '').replace('T', ' ').slice(5, 19) },
    { colKey: 'code', title: '代码', width: 90 },
    {
      colKey: 'side', title: '方向', width: 80,
      cell: ({ row }) => <span style={{ color: row.side === '买入' ? '#e34d59' : '#00a870' }}>{row.side}</span>,
    },
    { colKey: 'price', title: '价格', width: 90 },
    { colKey: 'qty', title: '数量', width: 80 },
    { colKey: 'amount', title: '金额', width: 100 },
    { colKey: 'strategy', title: '战法', width: 140, cell: ({ row }) => <span style={{ color: '#666' }}>{row.strategy}</span> },
  ]

  return (
    <div className="page">
      <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>📈 量化交易</div>
      <div style={{ fontSize: 12, color: '#888', marginBottom: 14 }}>实盘链路参数、仓位纪律与战法白名单（保存后约 5 秒热加载生效）</div>

      {loadErr && (
        <div style={{ marginBottom: 12, padding: '8px 12px', borderRadius: 6, background: '#fdecea', border: '1px solid #f5c6c2', color: '#b71c1c', fontSize: 12 }}>
          ⚠️ {loadErr}
        </div>
      )}

      {forbidden && (
        <div style={{ marginBottom: 12, padding: '18px 16px', borderRadius: 8, background: '#fff7e6', border: '1px solid #ffd591', color: '#ad6800', fontSize: 13 }}>
          🔒 无权限访问量化交易：当前登录「{api.getAccount() || '未知'}」为普通用户，该页面仅管理员账号可操作。请使用管理员账号（用户名 admin）登录后再进行管理。
        </div>
      )}

      <Card style={{ marginBottom: 14 }}>
        {state && state.enabled ? (
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', fontSize: 13 }}>
            <span style={{ color: state.last_probe_ok ? '#00a870' : '#666' }}>●</span>
            <span>首尔 ↔ 广州</span>
            <span style={{ fontFamily: 'monospace', color: '#4fc3f7' }}>{state.gateway_url}</span>
            {state.last_latency_ms > 0 && <Tag size="small"> {state.last_latency_ms}ms</Tag>}
            <Tag size="small" theme={state.tripped ? 'danger' : 'success'}>
              {state.tripped ? '熔断:' + (state.trip_reason || '未知') : '正常'}
            </Tag>
            <span>{state.mode === 'auto' ? '自动' : '手动'}</span>
            {fmtAgo(state.last_report_at) && <span>回报{fmtAgo(state.last_report_at)}</span>}
          </div>
        ) : state ? (
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', fontSize: 13 }}>
            <span style={{ color: form.enabled ? '#e6a23c' : '#666' }}>●</span>
            {form.enabled ? (
              <>
                <span>实盘链路已配置启用，但当前未连通网关</span>
                <span style={{ color: '#666', fontSize: 11 }}>请确认下方「网关地址」正确且广州网关在线，连通后此处转为实时状态</span>
              </>
            ) : (
              <>
                <span>实盘链路未启用</span>
                <span style={{ color: '#666', fontSize: 11 }}>打开下方「总开关」并配置网关地址后开始互通</span>
              </>
            )}
          </div>
        ) : (
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', fontSize: 13 }}>
            <span style={{ color: '#999' }}>●</span>
            <span style={{ color: '#666' }}>链路状态加载中（若长期停留请检查网络/重新登录）</span>
          </div>
        )}
      </Card>

      <Card title="总开关与执行方式" style={{ marginBottom: 14 }}>
        <Form labelWidth={120} labelAlign="right">
          <Form.FormItem label="实盘总开关">
            {syncing ? (
              <span style={{ fontSize: 13, color: '#999' }}>同步中…</span>
            ) : (
              <ToggleSw checked={form.enabled} onChange={(v) => { setForm({ ...form, enabled: v }); saveSwitches(v) }} />
            )}
            <span style={{ color: loadErr ? '#b71c1c' : '#00a870', fontSize: 11, marginLeft: 10 }}>
              {loadErr ? '⚠ 未同步服务器（下方为本地缓存，非真实状态）' : '已同步服务器 ✓'}
            </span>
            <span style={{ color: '#666', fontSize: 11, marginLeft: 10, display: 'block', marginTop: 4 }}>
              关闭后引擎不再向网关传递任何信号/建议（纸面盘不受影响）
            </span>
          </Form.FormItem>
          <Form.FormItem label="执行模式">
            <span style={segBtn(form.mode === 'manual')} onClick={() => saveMode('manual')}>手动确认</span>
            <span style={segBtn(form.mode === 'auto')} onClick={() => saveMode('auto')}>全自动</span>
            <span style={{ color: '#666', fontSize: 11, marginLeft: 10 }}>点击立即生效并保存；手动=每单前端确认；自动=信号直接下单</span>
          </Form.FormItem>
          <Form.FormItem label="委托价格">
            <span style={segBtn(form.price_type === 'market')} onClick={() => savePriceType('market')}>对手价</span>
            <span style={segBtn(form.price_type === 'limit')} onClick={() => savePriceType('limit')}>限价</span>
            <span style={{ color: '#666', fontSize: 11, marginLeft: 10 }}>点击立即生效并保存</span>
          </Form.FormItem>
          <Form.FormItem label="自动卖出">
            <ToggleSw checked={form.auto_sell} onChange={(v) => { setForm({ ...form, auto_sell: v }); saveAutoSell(v) }} />
            <span style={{ color: '#666', fontSize: 11, marginLeft: 10 }}>自动模式下止损/清仓级建议自动全仓卖出；止盈/减仓保持提醒</span>
          </Form.FormItem>
          <Form.FormItem label="心跳超时(秒)">
            <Input style={{ width: 140 }} type="number" value={form.miss_heartbeat_sec} min={30} max={3600}
              onChange={(v) => setForm({ ...form, miss_heartbeat_sec: parseInt(v, 10) })} />
            <span style={{ color: '#666', fontSize: 11, marginLeft: 10 }}>连续失联超过该值触发熔断暂停下单（30-3600）</span>
          </Form.FormItem>
          <Form.FormItem label="网关地址">
            <Input style={{ flex: 1, minWidth: 240 }} value={form.gateway_url} placeholder="http://81.71.69.17:8789"
              onChange={(v) => setForm({ ...form, gateway_url: v })} />
          </Form.FormItem>
          <Form.FormItem label="鉴权Token">
            <Input style={{ flex: 1, minWidth: 240 }} type="password" value={tokenInput} placeholder={form.token_masked || '未设置'}
              onChange={(v) => setTokenInput(v)} />
            <span style={{ color: '#666', fontSize: 11, marginLeft: 10 }}>显示为脱敏形态；留空表示保持原值不变</span>
          </Form.FormItem>
          <Form.FormItem>
            <Button theme="primary" onClick={saveExec} loading={saving}>保存网关参数</Button>
          </Form.FormItem>
        </Form>
      </Card>

      <Card title="仓位纪律" style={{ marginBottom: 14 }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 12 }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
            <label style={{ fontSize: 12, color: '#aaa' }}>最大持仓数</label>
            <Input type="number" value={form.max_positions} min={1} max={50} onChange={(v) => setForm({ ...form, max_positions: parseInt(v, 10) })} />
            <span style={{ fontSize: 10, color: '#666' }}>1-50，双端校验</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
            <label style={{ fontSize: 12, color: '#aaa' }}>单票金额(元)</label>
            <Input type="number" value={form.fixed_amount} min={0} step={500} onChange={(v) => setForm({ ...form, fixed_amount: parseFloat(v) })} />
            <span style={{ fontSize: 10, color: '#666' }}>每次买入投入金额</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
            <label style={{ fontSize: 12, color: '#aaa' }}>初始资金(元)</label>
            <Input type="number" value={form.initial_capital} min={0} step={10000} onChange={(v) => setForm({ ...form, initial_capital: parseFloat(v) })} />
            <span style={{ fontSize: 10, color: '#666' }}>用于仓位约束预检</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
            <label style={{ fontSize: 12, color: '#aaa' }}>单日买入笔数上限</label>
            <Input type="number" value={form.daily_max_buys} min={0} onChange={(v) => setForm({ ...form, daily_max_buys: parseInt(v, 10) })} />
            <span style={{ fontSize: 10, color: '#666' }}>0=不设限，防信号风暴</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
            <label style={{ fontSize: 12, color: '#aaa' }}>单日买入预算(元)</label>
            <Input type="number" value={form.daily_budget_amount} min={0} step={10000} onChange={(v) => setForm({ ...form, daily_budget_amount: parseFloat(v) })} />
            <span style={{ fontSize: 10, color: '#666' }}>0=不设限，超出拒绝新买入</span>
          </div>
        </div>
        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 10 }}>
          <Button theme="primary" onClick={saveCaps} loading={saving}>保存仓位纪律</Button>
        </div>
      </Card>

      <Card title="战法开关" style={{ marginBottom: 14 }}>
        <div style={{ fontSize: 11, color: '#666', marginBottom: 12 }}>关闭的战法信号不会进入实盘链路（模拟盘不受影响）；全部开启 = 不设白名单。因子/形态战法需先在「自动研究」页审批应用后才会出现在此处。</div>
        {strategyGroups.length === 0 ? (
          <div style={{ color: '#666', fontSize: 13, padding: '8px 2px' }}>暂无可用战法</div>
        ) : strategyGroups.map((grp) => (
          <div key={grp.kind} style={{ marginBottom: 14 }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#1d4ed8', margin: '4px 0 6px', paddingLeft: 4, borderLeft: '3px solid #1d4ed8' }}>
              {grp.label}
            </div>
            {grp.items.map((s) => (
              <div key={s.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10, padding: '9px 4px', borderBottom: '1px solid #ededed' }}>
                <div>
                  <div style={{ fontSize: 13, color: '#333' }}>{s.name}</div>
                  <div style={{ fontFamily: 'monospace', fontSize: 11, color: '#555', marginTop: 2 }}>{s.id}</div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 6, flex: 1, justifyContent: 'flex-end' }}>
                  <Input style={{ width: 100 }} type="number" min={0} step={500} value={amountsInput[s.id] ?? ''} placeholder="全局"
                    onChange={(v) => setAmountsInput({ ...amountsInput, [s.id]: v })} />
                  <span style={{ fontSize: 11, color: '#666' }}>元/次</span>
                  <ToggleSw checked={!!strategyOn[s.id]} onChange={(v) => { setStrategyOn({ ...strategyOn, [s.id]: v }); markStrategyDirty() }} />
                </div>
              </div>
            ))}
          </div>
        ))}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, justifyContent: 'flex-end', marginTop: 10 }}>
          <span style={{ fontSize: 11, color: '#666' }}>{strategyHint} · 仓位留空/0 = 使用全局单票金额</span>
          <Button theme="primary" disabled={!strategyDirty || saving} onClick={saveStrategies}>
            {saving ? '保存中…' : (strategyDirty ? '保存战法开关 *' : '已同步')}
          </Button>
        </div>
      </Card>

      <Card title="交易流水与整体盈亏" style={{ marginBottom: 14 }}>
        <div style={{ fontSize: 11, color: '#666', marginBottom: 12 }}>已实现=加权成本重放；浮动=市值-成本×数量；30s 刷新</div>
        {trades && trades.summary ? (
          <>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: 10, marginBottom: 12 }}>
              <div style={{ background: '#eef4fc', borderRadius: 8, padding: 10, textAlign: 'center', border: '1px solid #eef0f3' }}>
                <div style={{ fontSize: 18, fontWeight: 700, fontFamily: 'monospace', color: pnlColor(trades.summary.total_pnl) }}>{fmtMoney(trades.summary.total_pnl)}</div>
                <div style={{ fontSize: 11, color: '#777', marginTop: 3 }}>总盈亏</div>
              </div>
              <div style={{ background: '#eef4fc', borderRadius: 8, padding: 10, textAlign: 'center', border: '1px solid #eef0f3' }}>
                <div style={{ fontSize: 18, fontWeight: 700, fontFamily: 'monospace', color: pnlColor(trades.summary.realized_pnl) }}>{fmtMoney(trades.summary.realized_pnl)}</div>
                <div style={{ fontSize: 11, color: '#777', marginTop: 3 }}>已实现</div>
              </div>
              <div style={{ background: '#eef4fc', borderRadius: 8, padding: 10, textAlign: 'center', border: '1px solid #eef0f3' }}>
                <div style={{ fontSize: 18, fontWeight: 700, fontFamily: 'monospace', color: pnlColor(trades.summary.unrealized_pnl) }}>{fmtMoney(trades.summary.unrealized_pnl)}</div>
                <div style={{ fontSize: 11, color: '#777', marginTop: 3 }}>浮动盈亏</div>
              </div>
              <div style={{ background: '#eef4fc', borderRadius: 8, padding: 10, textAlign: 'center', border: '1px solid #eef0f3' }}>
                <div style={{ fontSize: 18, fontWeight: 700, fontFamily: 'monospace', color: '#1a1a1a' }}>{trades.summary.trade_count}</div>
                <div style={{ fontSize: 11, color: '#777', marginTop: 3 }}>成交笔数</div>
              </div>
              <div style={{ background: '#eef4fc', borderRadius: 8, padding: 10, textAlign: 'center', border: '1px solid #eef0f3' }}>
                <div style={{ fontSize: 18, fontWeight: 700, fontFamily: 'monospace', color: '#1a1a1a' }}>{trades.summary.wins}胜 / {trades.summary.losses}负</div>
                <div style={{ fontSize: 11, color: '#777', marginTop: 3 }}>卖出胜负</div>
              </div>
            </div>

            {(trades.by_strategy || []).length ? (
              <div style={{ marginBottom: 12 }}>
                <Table data={trades.by_strategy} columns={byStrategyColumns} rowKey="strategy" size="small" pagination={false} />
              </div>
            ) : (
              <div style={{ padding: '8px 2px', color: '#666', fontSize: 13 }}>暂无成交——实盘成交后此处出现按战法归因的盈亏统计（飞轮回流数据源）</div>
            )}

            {(trades.fills || []).length ? (
              <Table data={trades.fills} columns={fillsColumns} rowKey="order_id" size="small"
                pagination={{ pageSize: 10, showJumper: true }} />
            ) : null}
          </>
        ) : (
          <div style={{ color: '#666', fontSize: 13 }}>加载交易流水…</div>
        )}
      </Card>
    </div>
  )
}
