// web/src/components/DepthPanel.jsx
// ── 盘口面板组件 DepthPanel.jsx ──
// 展示个股买卖五档盘口、现价涨跌与委比/封单等派生因子，基于 Canvas 绘制。
import React, { useState, useEffect, useRef } from 'react'
import * as api from '../api/index.js'
import './DepthPanel.css'

// 配色（与 Vue 源完全一致）
const C = {
  bg: '#f7f8fa',
  lv: '#5b6b85',
  vol: '#5b6b85',
  nowBg: '#eef2f7',
  now: '#e8f0fe',
  ask: '#3ddc84',   // 卖盘绿
  bid: '#ff6b5a',   // 买盘红
  up: '#ff6b5a',
  down: '#3ddc84',
  src: '#5b8ff9',
}

/**
 * 格式化盘口价格为两位小数字符串，空/零值显示 "--"。
 * @param {number} v 价格
 * @returns {string}
 */
// 格式化价格，空值显示 --
function fmtPrice(v) {
  const n = Number(v) || 0
  return n ? n.toFixed(2) : '--'
}
/**
 * 格式化盘口量为中文单位（万），空/零值显示 "--"。
 * @param {number} v 委托量
 * @returns {string} 例如 "1.2万" / "--"
 */
// 格式化盘口量为中文单位
function fmtVol(v) {
  const n = Number(v) || 0
  if (n >= 1e4) return (n / 1e4).toFixed(1) + '万'
  return n ? String(Math.round(n)) : '--'
}

/**
 * 盘口面板组件
 * @param {{code:string, name?:string, height?:number}} props
 * @returns {JSX.Element}
 */
export default function DepthPanel({ code, name = '', height = 260 }) {
  const [ob, setOb] = useState({})
  const [factors, setFactors] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [dispName, setDispName] = useState(name)
  const [viewW, setViewW] = useState(320)

  const wrapRef = useRef(null)
  const canvasRef = useRef(null)

  // 拉取盘口（code 变化时重新加载）
  useEffect(() => {
    if (!code) return
    let cancelled = false
    async function load() {
      setLoading(true)
      setError('')
      try {
        const data = await api.fetchDepth(code)
        if (data && data.bids) {
          if (cancelled) return
          setOb(data)
          setFactors(data.factors || null)
          if (data.name) setDispName(data.name)
        } else {
          if (!cancelled) setError('盘口数据格式异常')
        }
      } catch (e) {
        if (!cancelled) setError(e && e.message ? e.message : '盘口加载失败')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    load()
    return () => { cancelled = true }
  }, [code])

  // 容器宽度自适应（ResizeObserver，退化轮询）
  useEffect(() => {
    if (!wrapRef.current) return
    setViewW(wrapRef.current.clientWidth)
    if (typeof ResizeObserver !== 'undefined') {
      const ro = new ResizeObserver(() => {
        if (wrapRef.current) setViewW(wrapRef.current.clientWidth)
      })
      ro.observe(wrapRef.current)
      return () => ro.disconnect()
    } else {
      const t = setInterval(() => {
        if (wrapRef.current) {
          const w = wrapRef.current.clientWidth
          setViewW((p) => (p === w ? p : w))
        }
      }, 500)
      return () => clearInterval(t)
    }
  }, [])

  // 现价相对昨收涨跌幅文本 + 颜色
  const pctText = (() => {
    const p = ob.price || 0
    const pc = ob.prev_close || 0
    if (!p || !pc) return '--'
    const d = (p - pc) / pc * 100
    return (d >= 0 ? '+' : '') + d.toFixed(2) + '%'
  })()
  const nowCls = pctText.startsWith('+') ? 'up' : 'down'

  // 绘制盘口阶梯（canvas，devicePixelRatio 缩放）
  useEffect(() => {
    const cvs = canvasRef.current
    if (!cvs || !ob || !ob.bids || !ob.bids.length) return

    const dpr = window.devicePixelRatio || 1
    const W = viewW
    const H = height
    cvs.width = Math.round(W * dpr)
    cvs.height = Math.round(H * dpr)
    cvs.style.width = W + 'px'
    cvs.style.height = H + 'px'
    const ctx = cvs.getContext('2d')
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
    ctx.clearRect(0, 0, W, H)
    ctx.fillStyle = C.bg
    ctx.fillRect(0, 0, W, H)

    // 档位
    const levels = Number(ob.levels) || Math.min(ob.bids.length || 0, 5) || 5 // 档位数：接口给定，缺省取买卖盘前 5 档
    const showLevels = Math.min(levels, 10) // 最多展示 10 档

    // 构建行：卖 high→low ... 现价 ... 买 low→high
    const rows = []
    for (let i = 0; i < showLevels; i++) {
      const label = showLevels - i
      const idx = showLevels - 1 - i
      const a = ob.asks ? ob.asks[idx] : null
      rows.push({ lv: '卖' + label, price: a ? a.price : 0, vol: a ? a.volume : 0, color: C.ask, best: i === showLevels - 1 })
    }
    rows.push({ now: true, lv: ob.name || code, price: ob.price || 0, volText: pctText, color: nowCls })
    for (let i = 0; i < showLevels; i++) {
      const label = i + 1
      const b = ob.bids ? ob.bids[i] : null
      rows.push({ lv: '买' + label, price: b ? b.price : 0, vol: b ? b.volume : 0, color: C.bid, best: i === 0 })
    }

    const factorH = factors ? 78 : 0          // 底部派生因子区高度（无因子则为 0）
    const rowH = (H - 8 - factorH) / rows.length // 每行高度（上下各留 4px）
    const col1 = 6, col1W = 56                // 第一列（档位标签）起点与宽度
    const priceX = col1 + col1W
    const priceW = (W - priceX) / 2           // 价格列占剩余宽度一半
    const volX = priceX + priceW              // 量/涨跌幅列起点

    ctx.font = '14px monospace'
    ctx.textBaseline = 'middle'

    rows.forEach((r, ri) => {
      const y = 4 + ri * rowH
      const cy = y + rowH / 2
      // 高亮最优档
      if (r.best) {
        ctx.fillStyle = 'rgba(0,0,0,0.03)'
        ctx.fillRect(col1, y, W - col1 * 2, rowH)
      }
      if (r.now) {
        ctx.fillStyle = C.nowBg
        ctx.fillRect(col1, y, W - col1 * 2, rowH)
        ctx.fillStyle = C.now
        ctx.textAlign = 'left'
        ctx.fillText(r.lv, col1, cy)
        const pcolor = r.color === 'up' ? C.up : C.down
        ctx.fillStyle = pcolor
        ctx.textAlign = 'right'
        ctx.fillText(fmtPrice(r.price), volX - 6, cy)
        ctx.fillStyle = C.vol
        ctx.fillText(r.volText, W - col1, cy)
      } else {
        ctx.fillStyle = C.lv
        ctx.textAlign = 'left'
        ctx.fillText(r.lv, col1, cy)
        ctx.fillStyle = r.color
        ctx.textAlign = 'right'
        ctx.fillText(fmtPrice(r.price), volX - 6, cy)
        ctx.fillStyle = C.vol
        ctx.fillText(fmtVol(r.vol), W - col1, cy)
      }
    })

    // 因子区
    if (factors) {
      let fy = H - factorH + 14
      ctx.font = '13px monospace'
      const labelColor = C.lv
      const drawRow = (items) => {
        let x = col1
        ctx.textAlign = 'left'
        items.forEach((it) => {
          ctx.fillStyle = labelColor
          ctx.fillText(it.label, x, fy)
          x += 52
          ctx.fillStyle = it.color || C.now
          ctx.fillText(it.val, x, fy)
          x += 70
        })
        fy += 22
      }
      const F = {
        bid_ask_ratio: Number(factors.bid_ask_ratio) || 0,
        bid_vol: Number(factors.bid_vol) || 0,
        ask_vol: Number(factors.ask_vol) || 0,
        seal_bid: Number(factors.seal_bid) || 0,
        seal_ask: Number(factors.seal_ask) || 0,
        spread_pct: Number(factors.spread_pct) || 0,
        near_pct: Number(factors.near_pct) || 0,
      }
      drawRow([
        { label: '委比', val: (F.bid_ask_ratio * 100).toFixed(1) + '%', color: F.bid_ask_ratio >= 0 ? C.up : C.down },
        { label: '买/卖量', val: fmtVol(F.bid_vol) + ' / ' + fmtVol(F.ask_vol) },
      ])
      drawRow([
        { label: '买一封单', val: fmtVol(F.seal_bid), color: C.up },
        { label: '卖一封单', val: fmtVol(F.seal_ask), color: C.down },
      ])
      drawRow([
        { label: '价差', val: F.spread_pct.toFixed(3) + '%' },
        { label: '覆盖', val: F.near_pct.toFixed(2) + '%' },
      ])
    }
  }, [ob, factors, viewW, height, pctText])

  return (
    <div className="depth-panel">
      <div className="depth-toolbar">
        <span className="depth-title">{ob.name || dispName || code} · 盘口</span>
        {ob.time ? (
          <span className="depth-time">
            {ob.time} {ob.source ? <i className="src">{ob.source}</i> : null}
          </span>
        ) : null}
        <button className="btn-refresh" disabled={loading} onClick={() => {
          setLoading(true); setError('')
          api.fetchDepth(code).then((data) => {
            if (data && data.bids) { setOb(data); setFactors(data.factors || null); if (data.name) setDispName(data.name) }
            else setError('盘口数据格式异常')
          }).catch((e) => setError(e && e.message ? e.message : '盘口加载失败')).finally(() => setLoading(false))
        }}>刷新</button>
      </div>

      {loading ? <div className="depth-state">加载中…</div> : null}
      {error ? <div className="depth-state">{error}</div> : null}

      {!loading && !error && ob.bids && ob.bids.length ? (
        <div ref={wrapRef}>
          <canvas ref={canvasRef} />
        </div>
      ) : null}
    </div>
  )
}

// web/src/components/DepthPanel.vue
<!--
  盘口面板 DepthPanel.vue（Order-book panel: 买卖五档 + 派生因子）
  展示个股买卖盘口：卖一~卖五 / 买一~买五 价格与委托量（手），以及委比、买卖压力、封单量等因子。
  免费数据源仅返回五档（Level-2 十档需付费），但后端数据结构按十档预留——
  组件按后端 levels 渲染实际返回档位数，接入十档数据源后无需改动。
  Displays a stock's order book: ask1~ask5 / bid1~bid5 prices & volumes, plus derived factors
  (bid-ask ratio, pressure, seal volumes). Free sources return 5 levels only (Level-2 costs money),
  but the backend pre-allocates 10; this component renders whatever `levels` the API reports, so
  switching to a Level-2 feed needs no frontend change.

  用法 / Usage:
    <DepthPanel :code="code" :height="220" />
  组件自管理加载：按 code 拉取 /api/depth/{code}，挂载即加载，code 变化自动刷新。
  The component loads itself: fetches /api/depth/{code} on mount for the given code and reloads when it changes.
-->
<template>
  <div class="depth-panel">
    <div class="depth-toolbar">
      <span class="depth-title">{{ ob.name || code }} · 盘口</span>
      <span v-if="ob.time" class="depth-time">{{ ob.time }} <i v-if="ob.source" class="src">{{ ob.source }}</i></span>
      <button class="btn-refresh" :disabled="loading" @click="load">刷新</button>
    </div>

    <div v-if="loading" class="depth-state">加载中…</div>
    <div v-else-if="error" class="depth-state">{{ error }}</div>

    <template v-else-if="ob.bids && ob.bids.length">
      <div class="depth-body">
        <!-- 卖盘（倒序：卖五在最上，卖一贴近现价） -->
        <div v-for="i in askRows" :key="'a' + i" class="depth-row ask">
          <span class="lv">{{ '卖' + askLabel(i) }}</span>
          <span class="px" :class="askColor(i)">{{ fmtPrice(ob.asks[askIdx(i)].price) }}</span>
          <span class="vol">{{ fmtVol(ob.asks[askIdx(i)].volume) }}</span>
        </div>

        <!-- 现价行 -->
        <div class="depth-row now">
          <span class="lv">{{ ob.name || code }}</span>
          <span class="px" :class="nowCls">{{ fmtPrice(ob.price) }}</span>
          <span class="vol">{{ pctText }}</span>
        </div>

        <!-- 买盘（正序：买一在最上） -->
        <div v-for="i in bidRows" :key="'b' + i" class="depth-row bid">
          <span class="lv">{{ '买' + bidLabel(i) }}</span>
          <span class="px" :class="bidColor(i)">{{ fmtPrice(ob.bids[bidIdx(i)].price) }}</span>
          <span class="vol">{{ fmtVol(ob.bids[bidIdx(i)].volume) }}</span>
        </div>
      </div>

      <!-- 因子区 -->
      <div v-if="factors" class="depth-factors">
        <div class="f-row">
          <span class="f-label">委比</span>
          <b :class="factors.bid_ask_ratio >= 0 ? 'up' : 'down'">
            {{ (factors.bid_ask_ratio * 100).toFixed(1) }}%
          </b>
          <span class="f-label">买/卖量</span>
          <b>{{ fmtVol(factors.bid_vol) }} / {{ fmtVol(factors.ask_vol) }}</b>
        </div>
        <div class="f-row">
          <span class="f-label">买一封单</span>
          <b class="up">{{ fmtVol(factors.seal_bid) }}</b>
          <span class="f-label">卖一封单</span>
          <b class="down">{{ fmtVol(factors.seal_ask) }}</b>
        </div>
        <div class="f-row">
          <span class="f-label">价差</span>
          <b>{{ factors.spread_pct.toFixed(3) }}%</b>
          <span class="f-label">覆盖</span>
          <b>{{ factors.near_pct.toFixed(2) }}%</b>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import * as api from '../api/index.js'

const props = defineProps({
  /** 股票代码（必填） */
  code: { type: String, required: true },
  /** 初始显示名称 */
  name: { type: String, default: '' },
  /** 面板高度（px），默认 260 */
  height: { type: Number, default: 260 },
})

const ob = ref({})
const factors = ref(null)
const loading = ref(false)
const error = ref('')
const name = ref(props.name)

// 实际档位数：后端 levels（免费源 5，十档接入后为 10）；无则按数组长度推导
const levels = computed(() => Number(ob.value.levels) || Math.min(ob.value.bids?.length || 0, 5) || 5)
const showLevels = computed(() => Math.min(levels.value, 10))

// 卖盘渲染行：最上层为第 showLevels 档（卖五/卖十），向下递减到卖一。
function askRows() { return Array.from({ length: showLevels.value }, (_, i) => i) }
function askLabel(i) { return showLevels.value - i }
function askIdx(i) { return showLevels.value - 1 - i }
// 买盘渲染行：最上层为买一，向下递增到第 showLevels 档。
function bidRows() { return Array.from({ length: showLevels.value }, (_, i) => i) }
function bidLabel(i) { return i + 1 }
function bidIdx(i) { return i }

function fmtPrice(v) {
  const n = Number(v) || 0
  return n ? n.toFixed(2) : '--'
}
function fmtVol(v) {
  const n = Number(v) || 0
  if (n >= 1e4) return (n / 1e4).toFixed(1) + '万'
  return n ? String(Math.round(n)) : '--'
}

const pctText = computed(() => {
  const p = ob.value.price || 0
  const pc = ob.value.prev_close || 0
  if (!p || !pc) return '--'
  const d = (p - pc) / pc * 100
  return (d >= 0 ? '+' : '') + d.toFixed(2) + '%'
})
const nowCls = computed(() => (pctText.value.startsWith('+') ? 'up' : 'down'))

function askColor(i) { return 'down' }   // 卖盘绿
function bidColor(i) { return 'up' }     // 买盘红

async function load() {
  if (!props.code) return
  loading.value = true
  error.value = ''
  try {
    const data = await api.fetchDepth(props.code)
    if (data && data.bids) {
      ob.value = data
      factors.value = data.factors || null
      if (data.name) name.value = data.name
    } else {
      error.value = '盘口数据格式异常'
    }
  } catch (e) {
    error.value = e && e.message ? e.message : '盘口加载失败'
  } finally {
    loading.value = false
  }
}

watch(() => props.code, () => {
  ob.value = {}
  factors.value = null
  name.value = props.name || ''
  load()
})

onMounted(load)
</script>

<style scoped>
.depth-panel {
  background: #101828;
  border-radius: 8px;
  padding: 8px 10px 10px;
  color: #cdd9e9;
  font-size: 14px;
}
.depth-toolbar {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 6px;
}
.depth-title { font-weight: 600; color: #e8f0fe; }
.depth-time { color: #7d8fab; font-size: 13px; }
.depth-time i.src { color: #5b8ff9; font-style: normal; margin-left: 4px; }
.btn-refresh {
  margin-left: auto;
  background: #1d2b45;
  color: #cdd9e9;
  border: 1px solid #2e4161;
  border-radius: 4px;
  padding: 2px 10px;
  cursor: pointer;
  font-size: 14px;
}
.btn-refresh:hover { background: #27406a; }
.btn-refresh:disabled { opacity: 0.55; cursor: default; }
.depth-state { text-align: center; padding: 18px 0; color: #8fa3bf; }
.depth-body {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.depth-row {
  display: grid;
  grid-template-columns: 56px 1fr 1fr;
  align-items: center;
  padding: 2px 6px;
  border-radius: 4px;
}
.depth-row .lv { color: #7d8fab; }
.depth-row .px { font-weight: 600; font-family: monospace; text-align: right; }
.depth-row .vol { text-align: right; font-family: monospace; color: #b8c7dd; }
.depth-row.ask .px { color: #3ddc84; }     /* 卖盘绿 */
.depth-row.bid .px { color: #ff6b5a; }     /* 买盘红 */
.depth-row.now { background: #16223a; }
.depth-row.now .px { color: #e8f0fe; }
.depth-row.now .lv { color: #e8f0fe; font-weight: 600; }
.depth-factors {
  margin-top: 8px;
  border-top: 1px solid #24334d;
  padding-top: 6px;
  display: flex;
  flex-direction: column;
  gap: 4px;
  font-size: 13px;
}
.f-row { display: flex; gap: 8px; align-items: center; }
.f-label { color: #7d8fab; min-width: 52px; }
.f-row b { color: #e8f0fe; font-weight: 600; font-family: monospace; min-width: 70px; }
.f-row b.up { color: #ff6b5a; }
.f-row b.down { color: #3ddc84; }
</style>
